/**
 * Tests for auto-develop execution improvements and loop fixes (adj-152.6).
 *
 * Covers:
 * - adj-152.6.1: buildExecuteReason includes parallel assignment instructions
 * - adj-152.6.2: Empty cycle prevention
 * - adj-152.6.3: idle-proposal-nudge skips auto-develop-enabled projects
 * - adj-152.6.4: Cycle counters count only current-cycle proposals
 * - adj-152.6.4: proposal:scored event handler updates cycle counter
 */

import { describe, it, expect, vi, beforeEach } from "vitest";

import type { AdjutantState } from "../../src/services/adjutant/state-store.js";
import type { CommunicationManager } from "../../src/services/adjutant/communication.js";
import type { BehaviorEvent } from "../../src/services/adjutant/behavior-registry.js";
import type { StimulusEngine } from "../../src/services/adjutant/stimulus-engine.js";
import type { ProposalStore } from "../../src/services/proposal-store.js";
import type { AutoDevelopStore, AutoDevelopCycle } from "../../src/services/auto-develop-store.js";
import type { Proposal } from "../../src/types/proposals.js";

// ---------------------------------------------------------------------------
// Mocks (hoisted)
// ---------------------------------------------------------------------------

const { mockGetAutoDevelopProjects, mockGetProject, mockPauseAutoDevelop, mockClearAutoDevelopPause } = vi.hoisted(() => ({
  mockGetAutoDevelopProjects: vi.fn().mockReturnValue({ success: true, data: [] }),
  mockGetProject: vi.fn().mockReturnValue({ success: false }),
  mockPauseAutoDevelop: vi.fn().mockReturnValue({ success: true }),
  mockClearAutoDevelopPause: vi.fn().mockReturnValue({ success: true }),
}));

vi.mock("../../src/services/projects-service.js", () => ({
  getAutoDevelopProjects: mockGetAutoDevelopProjects,
  getProject: mockGetProject,
  pauseAutoDevelop: mockPauseAutoDevelop,
  clearAutoDevelopPause: mockClearAutoDevelopPause,
}));

const { mockEmit } = vi.hoisted(() => ({
  mockEmit: vi.fn(),
}));

vi.mock("../../src/services/event-bus.js", () => ({
  getEventBus: () => ({ emit: mockEmit }),
}));

vi.mock("../../src/services/confidence-engine.js", () => ({
  classifyConfidence: (score: number) => {
    if (score >= 80) return "accept";
    if (score >= 60) return "refine";
    if (score >= 40) return "escalate";
    return "dismiss";
  },
}));

vi.mock("../../src/utils/index.js", () => ({
  logError: vi.fn(),
  logInfo: vi.fn(),
  logWarn: vi.fn(),
}));

vi.mock("../../src/services/escalation-builder.js", () => ({
  buildEscalationMessage: (projectName: string, proposals: { id: string }[]) => ({
    title: `Vision Update Needed — Project: ${projectName}`,
    body: `Escalation for ${proposals.length} proposal(s)`,
    proposalIds: proposals.map((p) => p.id),
    projectName,
  }),
}));

// Mock mcp-server for idle-proposal-nudge project context
const { mockGetProjectContextByAgent } = vi.hoisted(() => ({
  mockGetProjectContextByAgent: vi.fn().mockReturnValue(undefined),
}));

vi.mock("../../src/services/mcp-server.js", () => ({
  getProjectContextByAgent: mockGetProjectContextByAgent,
}));

import {
  createAutoDevelopLoop,
  buildPhaseReason,
} from "../../src/services/adjutant/behaviors/auto-develop-loop.js";
import { createIdleProposalNudge } from "../../src/services/adjutant/behaviors/idle-proposal-nudge.js";
import { dispatchToBehavior } from "../helpers/behavior-dispatch.js";

// ---------------------------------------------------------------------------
// Mock factories
// ---------------------------------------------------------------------------

function createMockStimulusEngine(): StimulusEngine {
  return {
    scheduleCheck: vi.fn().mockReturnValue("check-id-123"),
    cancelCheck: vi.fn(),
    onWake: vi.fn(),
    handleCriticalSignal: vi.fn(),
    registerWatch: vi.fn(),
    cancelWatch: vi.fn(),
    triggerWatch: vi.fn(),
    getPendingSchedule: vi.fn().mockReturnValue({ checks: [], watches: [] }),
    destroy: vi.fn(),
  } as unknown as StimulusEngine;
}

function createMockProposalStore(): ProposalStore {
  return {
    insertProposal: vi.fn(),
    getProposal: vi.fn().mockReturnValue(null),
    getProposals: vi.fn().mockReturnValue([]),
    updateProposalStatus: vi.fn(),
    insertComment: vi.fn(),
    getComments: vi.fn().mockReturnValue([]),
    reviseProposal: vi.fn(),
    getRevisions: vi.fn().mockReturnValue([]),
    setConfidenceScore: vi.fn(),
    incrementReviewRound: vi.fn(),
    getAutoGeneratedProposals: vi.fn().mockReturnValue([]),
    getProposalsByConfidenceRange: vi.fn().mockReturnValue([]),
  } as unknown as ProposalStore;
}

function createMockAutoDevelopStore(): AutoDevelopStore {
  const mockCycle: AutoDevelopCycle = {
    id: "cycle-1",
    projectId: "proj-1",
    phase: "analyze",
    startedAt: "2026-03-26T00:00:00.000Z",
    completedAt: null,
    proposalsGenerated: 0,
    proposalsAccepted: 0,
    proposalsEscalated: 0,
    proposalsDismissed: 0,
    escalationCount: 0,
    lastEscalationAt: null,
  };
  return {
    startCycle: vi.fn().mockReturnValue(mockCycle),
    updateCycle: vi.fn().mockReturnValue(mockCycle),
    completeCycle: vi.fn().mockReturnValue({ ...mockCycle, completedAt: new Date().toISOString() }),
    getActiveCycle: vi.fn().mockReturnValue(null),
    getCycleHistory: vi.fn().mockReturnValue([]),
  };
}

function createMockState(): AdjutantState {
  return {
    getAgentProfile: vi.fn().mockReturnValue(null),
    upsertAgentProfile: vi.fn(),
    getAllAgentProfiles: vi.fn().mockReturnValue([]),
    incrementAssignmentCount: vi.fn(),
    logDecision: vi.fn(),
    getRecentDecisions: vi.fn().mockReturnValue([]),
    getMeta: vi.fn().mockReturnValue(null),
    setMeta: vi.fn(),
    pruneOldDecisions: vi.fn(),
    logSpawn: vi.fn(),
    getSpawnHistory: vi.fn().mockReturnValue([]),
    getAgentSpawnHistory: vi.fn().mockReturnValue([]),
    markDecommissioned: vi.fn(),
    getLastSpawn: vi.fn().mockReturnValue(null),
    countActiveSpawns: vi.fn().mockReturnValue(0),
    markAllDisconnected: vi.fn().mockReturnValue(0),
    recordOutcome: vi.fn(),
    getRecentDecisionsWithOutcomes: vi.fn().mockReturnValue([]),
    getDecisionsForTarget: vi.fn().mockReturnValue([]),
    isCoordinator: vi.fn().mockReturnValue(false),
    getAgentsByRole: vi.fn().mockReturnValue([]),
  } as unknown as AdjutantState;
}

function createMockComm(): CommunicationManager {
  return {
    queueRoutine: vi.fn(),
    sendImportant: vi.fn().mockResolvedValue(undefined),
    escalate: vi.fn().mockResolvedValue(undefined),
    messageAgent: vi.fn().mockResolvedValue(undefined),
    flushRoutineQueue: vi.fn().mockReturnValue([]),
    getRoutineQueueLength: vi.fn().mockReturnValue(0),
  };
}

const MOCK_PROJECT = {
  id: "proj-1",
  name: "test-project",
  path: "/tmp/test",
  mode: "swarm" as const,
  sessions: [],
  createdAt: new Date().toISOString(),
  active: true,
  autoDevelop: true,
  autoDevelopPausedAt: undefined,
  visionContext: "Build a better world",
};

function makeEvent(name: string, data: unknown = {}): BehaviorEvent {
  return { name: name as BehaviorEvent["name"], data, seq: 1 };
}

function makeProposal(overrides: Partial<Proposal> = {}): Proposal {
  return {
    id: "prop-1",
    author: "agent-1",
    title: "Test Proposal",
    description: "A test proposal",
    type: "engineering",
    status: "pending",
    project: "proj-1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reviewRound: 0,
    autoGenerated: false,
    ...overrides,
  };
}

// ===========================================================================
// Tests
// ===========================================================================

describe("Auto-develop execution improvements (adj-152.6)", () => {
  let stimulusEngine: StimulusEngine;
  let proposalStore: ProposalStore;
  let autoDevelopStore: AutoDevelopStore;
  let state: AdjutantState;
  let comm: CommunicationManager;

  beforeEach(() => {
    vi.clearAllMocks();
    stimulusEngine = createMockStimulusEngine();
    proposalStore = createMockProposalStore();
    autoDevelopStore = createMockAutoDevelopStore();
    state = createMockState();
    comm = createMockComm();
  });

  // -------------------------------------------------------------------------
  // adj-152.6.1: buildExecuteReason includes parallel assignment instructions
  // -------------------------------------------------------------------------

  describe("buildExecuteReason — parallel assignment instructions (adj-152.6.1)", () => {
    it("should include parallel execution dependency analysis instructions", () => {
      const reason = buildPhaseReason(
        "proj-1",
        "test-project",
        "execute",
        proposalStore,
        autoDevelopStore,
        state,
      );

      expect(reason).toContain("PARALLEL EXECUTION");
      expect(reason).toContain("DEPENDENCY ANALYSIS");
      expect(reason).toContain("INDEPENDENT");
      expect(reason).toContain("DEPENDENT");
      expect(reason).toContain("spawn_worker");
      expect(reason).toContain("ALL agents are done");
    });

    it("should instruct coordinator to check dependency chains before spawning", () => {
      const reason = buildPhaseReason(
        "proj-1",
        "test-project",
        "execute",
        proposalStore,
        autoDevelopStore,
        state,
      );

      expect(reason).toContain("list_beads");
      expect(reason).toContain("dependency chain");
      expect(reason).toContain("shared dependency chains");
    });
  });

  // -------------------------------------------------------------------------
  // adj-152.6.2: Empty cycle prevention
  // -------------------------------------------------------------------------

  describe("empty cycle prevention (adj-152.6.2)", () => {
    it("should not create a cycle when no proposals exist after a previous cycle completed", async () => {
      mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [MOCK_PROJECT] });

      // No active cycle
      (autoDevelopStore.getActiveCycle as ReturnType<typeof vi.fn>).mockReturnValue(null);

      // A previous cycle exists (we've looped back)
      (autoDevelopStore.getCycleHistory as ReturnType<typeof vi.fn>).mockReturnValue([
        {
          id: "old-cycle",
          projectId: "proj-1",
          phase: "validate",
          startedAt: "2026-03-25T00:00:00Z",
          completedAt: "2026-03-25T12:00:00Z",
          proposalsGenerated: 2,
          proposalsAccepted: 1,
          proposalsEscalated: 0,
          proposalsDismissed: 1,
          escalationCount: 0,
          lastEscalationAt: null,
        },
      ]);

      // No proposals at all
      (proposalStore.getProposals as ReturnType<typeof vi.fn>).mockReturnValue([]);

      // Phase is analyze (default when getMeta returns null)
      (state.getMeta as ReturnType<typeof vi.fn>).mockReturnValue(null);

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", {});
      await dispatchToBehavior(behavior, event, state, comm);

      // Should NOT have started a cycle
      expect(autoDevelopStore.startCycle).not.toHaveBeenCalled();

      // Should have logged the empty cycle prevention decision
      expect(state.logDecision).toHaveBeenCalledWith(
        expect.objectContaining({
          action: "empty_cycle_prevention",
          target: "proj-1",
        }),
      );

      // Should transition to ideate
      expect(state.setMeta).toHaveBeenCalledWith(
        expect.stringContaining("phase_proj-1"),
        "ideate",
      );
    });

    it("should create a cycle when pending proposals exist even after previous cycle", async () => {
      mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [MOCK_PROJECT] });

      // No active cycle
      (autoDevelopStore.getActiveCycle as ReturnType<typeof vi.fn>).mockReturnValue(null);

      // A previous cycle exists
      (autoDevelopStore.getCycleHistory as ReturnType<typeof vi.fn>).mockReturnValue([
        {
          id: "old-cycle",
          projectId: "proj-1",
          phase: "validate",
          startedAt: "2026-03-25T00:00:00Z",
          completedAt: "2026-03-25T12:00:00Z",
          proposalsGenerated: 2,
          proposalsAccepted: 1,
          proposalsEscalated: 0,
          proposalsDismissed: 1,
          escalationCount: 0,
          lastEscalationAt: null,
        },
      ]);

      // Has pending proposals
      (proposalStore.getProposals as ReturnType<typeof vi.fn>).mockImplementation(
        (opts?: { status?: string }) => {
          if (opts?.status === "pending") return [makeProposal()];
          return [];
        },
      );

      // Phase is analyze
      (state.getMeta as ReturnType<typeof vi.fn>).mockReturnValue(null);

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", {});
      await dispatchToBehavior(behavior, event, state, comm);

      // Should have started a cycle since there are pending proposals
      expect(autoDevelopStore.startCycle).toHaveBeenCalled();
    });

    it("should allow first cycle even with no proposals (no previous cycles)", async () => {
      mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [MOCK_PROJECT] });

      // No active cycle
      (autoDevelopStore.getActiveCycle as ReturnType<typeof vi.fn>).mockReturnValue(null);

      // No previous cycles (first time)
      (autoDevelopStore.getCycleHistory as ReturnType<typeof vi.fn>).mockReturnValue([]);

      // No proposals at all
      (proposalStore.getProposals as ReturnType<typeof vi.fn>).mockReturnValue([]);

      // Phase is analyze
      (state.getMeta as ReturnType<typeof vi.fn>).mockReturnValue(null);

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", {});
      await dispatchToBehavior(behavior, event, state, comm);

      // Should create a cycle — first time, even with no proposals
      expect(autoDevelopStore.startCycle).toHaveBeenCalled();
    });
  });

  // -------------------------------------------------------------------------
  // adj-152.6.3: idle-proposal-nudge skips auto-develop-enabled projects
  // -------------------------------------------------------------------------

  describe("idle-proposal-nudge auto-develop awareness (adj-152.6.3)", () => {
    it("should skip nudge when agent's project has auto-develop enabled", async () => {
      const nudgeBehavior = createIdleProposalNudge(stimulusEngine, proposalStore);

      // Agent is connected and idle
      (state.getAgentProfile as ReturnType<typeof vi.fn>).mockReturnValue({
        agentId: "agent-1",
        lastStatus: "idle",
        disconnectedAt: null,
        connectedAt: "2026-03-26T10:00:00Z",
      });

      // Agent has a project context
      mockGetProjectContextByAgent.mockReturnValue({
        projectId: "proj-1",
        projectName: "test-project",
        projectPath: "/tmp/test",
        beadsDir: "/tmp/test/.beads",
      });

      // Project has auto-develop enabled
      mockGetProject.mockReturnValue({
        success: true,
        data: { ...MOCK_PROJECT, autoDevelop: true },
      });

      const event: BehaviorEvent = {
        name: "agent:status_changed",
        data: { agent: "agent-1", status: "idle" },
        seq: 1,
      };

      await dispatchToBehavior(nudgeBehavior, event, state, comm);

      // Should NOT have scheduled a check
      expect(stimulusEngine.scheduleCheck).not.toHaveBeenCalled();

      // Should have logged the skip decision
      expect(state.logDecision).toHaveBeenCalledWith(
        expect.objectContaining({
          action: "skipped_auto_develop_project",
          target: "agent-1",
        }),
      );
    });

    it("should proceed with nudge when agent's project does NOT have auto-develop", async () => {
      const nudgeBehavior = createIdleProposalNudge(stimulusEngine, proposalStore);

      (state.getAgentProfile as ReturnType<typeof vi.fn>).mockReturnValue({
        agentId: "agent-1",
        lastStatus: "idle",
        disconnectedAt: null,
        connectedAt: "2026-03-26T10:00:00Z",
      });

      mockGetProjectContextByAgent.mockReturnValue({
        projectId: "proj-2",
        projectName: "other-project",
        projectPath: "/tmp/other",
        beadsDir: "/tmp/other/.beads",
      });

      // Project does NOT have auto-develop
      mockGetProject.mockReturnValue({
        success: true,
        data: { ...MOCK_PROJECT, id: "proj-2", autoDevelop: false },
      });

      const event: BehaviorEvent = {
        name: "agent:status_changed",
        data: { agent: "agent-1", status: "idle" },
        seq: 1,
      };

      await dispatchToBehavior(nudgeBehavior, event, state, comm);

      // Should have scheduled a check (nudge proceeds normally)
      expect(stimulusEngine.scheduleCheck).toHaveBeenCalled();
    });
  });

  // -------------------------------------------------------------------------
  // adj-152.6.4: Cycle counters count only current-cycle proposals
  // -------------------------------------------------------------------------

  describe("cycle counter sync — per-cycle filtering (adj-152.6.4)", () => {
    it("should pass createdAfter filter matching cycle startedAt when syncing counters", async () => {
      const cycleStartedAt = "2026-03-26T12:00:00.000Z";

      mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [MOCK_PROJECT] });

      // Active cycle exists
      const activeCycle: AutoDevelopCycle = {
        id: "cycle-1",
        projectId: "proj-1",
        phase: "review",
        startedAt: cycleStartedAt,
        completedAt: null,
        proposalsGenerated: 0,
        proposalsAccepted: 0,
        proposalsEscalated: 0,
        proposalsDismissed: 0,
        escalationCount: 0,
        lastEscalationAt: null,
      };
      (autoDevelopStore.getActiveCycle as ReturnType<typeof vi.fn>).mockReturnValue(activeCycle);

      // Phase is review (coordinator-driven, so no auto-advance)
      (state.getMeta as ReturnType<typeof vi.fn>).mockImplementation((key: string) => {
        if (key.includes("phase_")) return "review";
        return null;
      });

      // Return proposals only when createdAfter filter matches
      (proposalStore.getProposals as ReturnType<typeof vi.fn>).mockImplementation(
        (opts?: { status?: string; createdAfter?: string }) => {
          // Only return proposals for the cycle-scoped filter
          if (opts?.createdAfter === cycleStartedAt) {
            if (opts?.status === "accepted") return [makeProposal({ status: "accepted" })];
            if (opts?.status === "dismissed") return [];
            return [makeProposal(), makeProposal({ id: "prop-2" })];
          }
          // Queries without createdAfter (e.g. for backpressure checks) return more
          return [makeProposal(), makeProposal({ id: "prop-2" }), makeProposal({ id: "prop-old", createdAt: "2026-03-25T00:00:00Z" })];
        },
      );

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("agent:status_changed", { status: "done", agent: "agent-1" });
      await dispatchToBehavior(behavior, event, state, comm);

      // updateCycle should be called with cycle-scoped counts
      expect(autoDevelopStore.updateCycle).toHaveBeenCalledWith(
        "cycle-1",
        expect.objectContaining({
          proposalsGenerated: 2,
          proposalsAccepted: 1,
        }),
      );
    });
  });

  // -------------------------------------------------------------------------
  // adj-152.6.4: proposal:scored event handler updates cycle counter
  // -------------------------------------------------------------------------

  describe("proposal:scored event handler (adj-152.6.4)", () => {
    it("should update cycle counters when a proposal:scored event fires", async () => {
      const cycleStartedAt = "2026-03-26T12:00:00.000Z";

      mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [MOCK_PROJECT] });

      // Active cycle exists
      const activeCycle: AutoDevelopCycle = {
        id: "cycle-1",
        projectId: "proj-1",
        phase: "review",
        startedAt: cycleStartedAt,
        completedAt: null,
        proposalsGenerated: 0,
        proposalsAccepted: 0,
        proposalsEscalated: 0,
        proposalsDismissed: 0,
        escalationCount: 0,
        lastEscalationAt: null,
      };
      (autoDevelopStore.getActiveCycle as ReturnType<typeof vi.fn>).mockReturnValue(activeCycle);

      // Phase is review
      (state.getMeta as ReturnType<typeof vi.fn>).mockImplementation((key: string) => {
        if (key.includes("phase_")) return "review";
        return null;
      });

      const scoredProposal = makeProposal({
        status: "pending",
        confidenceScore: 85,
        createdAt: "2026-03-26T13:00:00.000Z",
      });

      (proposalStore.getProposals as ReturnType<typeof vi.fn>).mockImplementation(
        (opts?: { status?: string; createdAfter?: string }) => {
          if (opts?.createdAfter === cycleStartedAt) {
            if (opts?.status === "accepted") return [];
            if (opts?.status === "dismissed") return [];
            return [scoredProposal];
          }
          return [scoredProposal];
        },
      );

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("proposal:scored", {
        proposalId: "prop-1",
        projectId: "proj-1",
        score: 85,
        classification: "accept",
        reviewRound: 0,
      });

      await dispatchToBehavior(behavior, event, state, comm);

      // The proposal:scored handler should have called updateCycle
      // (first call is from the handler, second may come from the main loop body)
      expect(autoDevelopStore.updateCycle).toHaveBeenCalledWith(
        "cycle-1",
        expect.objectContaining({
          proposalsGenerated: 1,
        }),
      );
    });
  });
});
