import { describe, it, expect, vi, beforeEach } from "vitest";

// Mock logger before imports
vi.mock("../../src/utils/index.js", () => ({
  logInfo: vi.fn(),
  logWarn: vi.fn(),
  logError: vi.fn(),
  logDebug: vi.fn(),
}));

// Mock mcp-server
const { mockGetAgentBySession, mockGetProjectContextBySession, mockResolveToolProjectContext } = vi.hoisted(() => {
  return {
    mockGetAgentBySession: vi.fn(),
    mockGetProjectContextBySession: vi.fn(),
    mockResolveToolProjectContext: vi.fn(),
  };
});

vi.mock("../../src/services/mcp-server.js", () => ({
  getAgentBySession: mockGetAgentBySession,
  getProjectContextBySession: mockGetProjectContextBySession,
  resolveToolProjectContext: mockResolveToolProjectContext,
}));

// Mock event-bus
const { mockEmit } = vi.hoisted(() => {
  return {
    mockEmit: vi.fn(),
  };
});

vi.mock("../../src/services/event-bus.js", () => ({
  getEventBus: () => ({ emit: mockEmit }),
}));

// Mock projects-service (getProject for auto-develop check)
const { mockGetProject } = vi.hoisted(() => {
  return {
    mockGetProject: vi.fn(),
  };
});

vi.mock("../../src/services/projects-service.js", () => ({
  enableAutoDevelop: vi.fn(),
  disableAutoDevelop: vi.fn(),
  setVisionContext: vi.fn(),
  clearAutoDevelopPause: vi.fn(),
  getProject: mockGetProject,
}));

// Mock bd-client (for checkOpenCriticalBugs)
const { mockExecBd } = vi.hoisted(() => {
  return {
    mockExecBd: vi.fn().mockResolvedValue({ success: true, data: [] }),
  };
});

vi.mock("../../src/services/bd-client.js", () => ({
  execBd: mockExecBd,
  executeBd: vi.fn(),
}));

// Mock MCP SDK
const { mockTool, MockMcpServer } = vi.hoisted(() => {
  const mockTool = vi.fn();
  const MockMcpServer = vi.fn().mockImplementation(function () {
    return {
      tool: mockTool,
      connect: vi.fn().mockResolvedValue(undefined),
      close: vi.fn().mockResolvedValue(undefined),
      server: {},
    };
  });
  return { mockTool, MockMcpServer };
});

vi.mock("@modelcontextprotocol/sdk/server/mcp.js", () => ({
  McpServer: MockMcpServer,
}));

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { ProposalStore } from "../../src/services/proposal-store.js";
import { registerAutoDevelopTools } from "../../src/services/mcp-tools/auto-develop.js";
import { logInfo } from "../../src/utils/index.js";

// =============================================================================
// Helpers
// =============================================================================

function createMockServer(): McpServer {
  return new MockMcpServer() as unknown as McpServer;
}

function createMockStore(): ProposalStore {
  return {
    insertProposal: vi.fn(),
    getProposal: vi.fn().mockReturnValue({
      id: "test-uuid",
      author: "test-agent",
      title: "Test Proposal",
      description: "A test proposal",
      type: "engineering",
      project: "proj-123",
      status: "pending",
      createdAt: "2026-03-11T00:00:00Z",
      updatedAt: "2026-03-11T00:00:00Z",
      reviewRound: 1,
      autoGenerated: true,
    }),
    getProposals: vi.fn().mockReturnValue([]),
    updateProposalStatus: vi.fn(),
    insertComment: vi.fn(),
    getComments: vi.fn(),
    reviseProposal: vi.fn(),
    getRevisions: vi.fn(),
    setConfidenceScore: vi.fn(),
    incrementReviewRound: vi.fn(),
    getAutoGeneratedProposals: vi.fn(),
    getProposalsByConfidenceRange: vi.fn(),
  } as unknown as ProposalStore;
}

/**
 * Helper to extract the tool handler registered with server.tool().
 */
function getToolHandler(
  store: ProposalStore,
  toolName: string,
  deps?: { adjutantState?: unknown; stimulusEngine?: unknown },
): (...args: unknown[]) => Promise<unknown> {
  mockTool.mockClear();
  const server = createMockServer();
  const mockAutoDevelopStore = {
    getActiveCycle: vi.fn().mockReturnValue({ id: "cycle-1" }),
    getCycleHistory: vi.fn().mockReturnValue([]),
    startCycle: vi.fn(),
    updateCycle: vi.fn(),
    completeCycle: vi.fn(),
  };
  registerAutoDevelopTools(
    server,
    store,
    mockAutoDevelopStore as unknown as Parameters<typeof registerAutoDevelopTools>[2],
    deps as Parameters<typeof registerAutoDevelopTools>[3],
  );

  const call = mockTool.mock.calls.find(
    (c: unknown[]) => c[0] === toolName,
  );
  if (!call) {
    throw new Error(`Tool "${toolName}" not registered`);
  }
  // call[2] is the handler function (name, schema, handler)
  return call[2] as (...args: unknown[]) => Promise<unknown>;
}

// =============================================================================
// score_proposal
// =============================================================================

describe("score_proposal MCP tool", () => {
  const SESSION_ID = "session-123";
  const PROJECT_CONTEXT = {
    projectId: "proj-123",
    projectName: "adjutant",
    projectPath: "/code/adjutant",
    beadsDir: "/code/adjutant/.beads",
  };

  beforeEach(() => {
    vi.clearAllMocks();
    mockGetAgentBySession.mockReturnValue("reviewer-agent");
    mockGetProjectContextBySession.mockReturnValue(PROJECT_CONTEXT);
    mockGetProject.mockReturnValue({
      success: true,
      data: { id: "proj-123", name: "adjutant", autoDevelop: true },
    });
    mockEmit.mockClear();
  });

  it("should compute and store confidence score for valid input", async () => {
    const store = createMockStore();
    const handler = getToolHandler(store, "score_proposal");

    const result = await handler(
      {
        proposalId: "test-uuid",
        reviewerConsensus: 80,
        specClarity: 70,
        codebaseAlignment: 60,
        riskAssessment: 50,
        historicalSuccess: 40,
      },
      { sessionId: SESSION_ID },
    );

    // Verify score was stored
    expect(store.setConfidenceScore).toHaveBeenCalledWith(
      "test-uuid",
      64, // weighted sum: 0.3*80 + 0.2*70 + 0.2*60 + 0.15*50 + 0.15*40 = 63.5 -> 64
      {
        reviewerConsensus: 80,
        specClarity: 70,
        codebaseAlignment: 60,
        riskAssessment: 50,
        historicalSuccess: 40,
      },
    );

    // Verify event was emitted
    expect(mockEmit).toHaveBeenCalledWith("proposal:scored", {
      proposalId: "test-uuid",
      projectId: "proj-123",
      score: 64,
      classification: "refine",
      reviewRound: 1,
    });

    // Verify response
    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    expect(parsed.score).toBe(64);
    expect(parsed.classification).toBe("refine");
    expect(parsed.signals.reviewerConsensus).toBe(80);
  });

  it("should return error when session is unknown (no agent)", async () => {
    mockGetAgentBySession.mockReturnValue(undefined);
    const store = createMockStore();
    const handler = getToolHandler(store, "score_proposal");

    const result = await handler(
      {
        proposalId: "test-uuid",
        reviewerConsensus: 80,
        specClarity: 70,
        codebaseAlignment: 60,
        riskAssessment: 50,
        historicalSuccess: 40,
      },
      { sessionId: SESSION_ID },
    );

    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    expect(parsed.error).toContain("Unknown session");
    expect(store.setConfidenceScore).not.toHaveBeenCalled();
  });

  it("should return error when proposal is not found", async () => {
    const store = createMockStore();
    (store.getProposal as ReturnType<typeof vi.fn>).mockReturnValue(null);
    const handler = getToolHandler(store, "score_proposal");

    const result = await handler(
      {
        proposalId: "nonexistent-uuid",
        reviewerConsensus: 80,
        specClarity: 70,
        codebaseAlignment: 60,
        riskAssessment: 50,
        historicalSuccess: 40,
      },
      { sessionId: SESSION_ID },
    );

    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    expect(parsed.error).toBe("Proposal not found");
    expect(store.setConfidenceScore).not.toHaveBeenCalled();
  });

  it("should score proposal from a different project (adj-136: cross-project scoring allowed)", async () => {
    // Agents spawned to review cross-project proposals should be able to score them.
    // score_proposal derives the project from the proposal itself, not the agent's session.
    const store = createMockStore();
    (store.getProposal as ReturnType<typeof vi.fn>).mockReturnValue({
      id: "test-uuid",
      author: "test-agent",
      title: "Test",
      description: "test",
      type: "engineering",
      project: "other-project-id",
      status: "pending",
      createdAt: "2026-03-11T00:00:00Z",
      updatedAt: "2026-03-11T00:00:00Z",
      reviewRound: 0,
      autoGenerated: false,
    });
    // getProject is called with the proposal's project, not the session's
    mockGetProject.mockReturnValue({
      success: true,
      data: { id: "other-project-id", name: "auto-tank", autoDevelop: true },
    });
    const handler = getToolHandler(store, "score_proposal");

    const result = await handler(
      {
        proposalId: "test-uuid",
        reviewerConsensus: 80,
        specClarity: 70,
        codebaseAlignment: 60,
        riskAssessment: 50,
        historicalSuccess: 40,
      },
      { sessionId: SESSION_ID },
    );

    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    expect(parsed).toHaveProperty("score");
    expect(store.setConfidenceScore).toHaveBeenCalled();
  });

  it("should score proposal even without session project context (adj-136)", async () => {
    // Agents may lack project context but should still score proposals
    // since project is derived from the proposal itself.
    mockGetProjectContextBySession.mockReturnValue(undefined);
    const store = createMockStore();
    const handler = getToolHandler(store, "score_proposal");

    const result = await handler(
      {
        proposalId: "test-uuid",
        reviewerConsensus: 80,
        specClarity: 70,
        codebaseAlignment: 60,
        riskAssessment: 50,
        historicalSuccess: 40,
      },
      { sessionId: SESSION_ID },
    );

    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    // Should succeed — project derived from proposal, not session context
    expect(parsed).toHaveProperty("score");
    expect(store.setConfidenceScore).toHaveBeenCalled();
  });

  it("should log confidence_gate_decision with all relevant fields (adj-122.9.2)", async () => {
    const store = createMockStore();
    const handler = getToolHandler(store, "score_proposal");

    await handler(
      {
        proposalId: "test-uuid",
        reviewerConsensus: 80,
        specClarity: 70,
        codebaseAlignment: 60,
        riskAssessment: 50,
        historicalSuccess: 40,
      },
      { sessionId: SESSION_ID },
    );

    expect(logInfo).toHaveBeenCalledWith("confidence_gate_decision", {
      proposalId: "test-uuid",
      projectId: "proj-123",
      score: 64,
      classification: "refine",
      signals: {
        reviewerConsensus: 80,
        specClarity: 70,
        codebaseAlignment: 60,
        riskAssessment: 50,
        historicalSuccess: 40,
      },
      reviewRound: 1,
      scoredBy: "reviewer-agent",
    });
  });

  it("should return error when auto-develop is not enabled for project (adj-122.9.4)", async () => {
    mockGetProject.mockReturnValue({
      success: true,
      data: { id: "proj-123", name: "adjutant", autoDevelop: false },
    });
    const store = createMockStore();
    const handler = getToolHandler(store, "score_proposal");

    const result = await handler(
      {
        proposalId: "test-uuid",
        reviewerConsensus: 80,
        specClarity: 70,
        codebaseAlignment: 60,
        riskAssessment: 50,
        historicalSuccess: 40,
      },
      { sessionId: SESSION_ID },
    );

    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    expect(parsed.error).toContain("Auto-develop is not enabled");
    expect(store.setConfidenceScore).not.toHaveBeenCalled();
  });

  it("should return error when project lookup fails (adj-122.9.4)", async () => {
    mockGetProject.mockReturnValue({
      success: false,
      error: { code: "NOT_FOUND", message: "Project not found" },
    });
    const store = createMockStore();
    const handler = getToolHandler(store, "score_proposal");

    const result = await handler(
      {
        proposalId: "test-uuid",
        reviewerConsensus: 80,
        specClarity: 70,
        codebaseAlignment: 60,
        riskAssessment: 50,
        historicalSuccess: 40,
      },
      { sessionId: SESSION_ID },
    );

    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    expect(parsed.error).toContain("Project not found");
    expect(store.setConfidenceScore).not.toHaveBeenCalled();
  });

  it("should classify high-confidence proposals as accept", async () => {
    const store = createMockStore();
    const handler = getToolHandler(store, "score_proposal");

    const result = await handler(
      {
        proposalId: "test-uuid",
        reviewerConsensus: 90,
        specClarity: 90,
        codebaseAlignment: 90,
        riskAssessment: 90,
        historicalSuccess: 90,
      },
      { sessionId: SESSION_ID },
    );

    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    expect(parsed.score).toBe(90);
    expect(parsed.classification).toBe("accept");
  });
});

// =============================================================================
// advance_auto_develop_phase (adj-135)
// =============================================================================

describe("advance_auto_develop_phase MCP tool", () => {
  const SESSION_ID = "session-123";
  const PROJECT_CONTEXT = {
    projectId: "proj-123",
    projectName: "adjutant",
    projectPath: "/code/adjutant",
    beadsDir: "/code/adjutant/.beads",
  };

  function createMockDeps() {
    return {
      adjutantState: {
        getMeta: vi.fn().mockReturnValue("analyze"),
        setMeta: vi.fn(),
        logDecision: vi.fn(),
        countActiveSpawns: vi.fn().mockReturnValue(0),
      },
      stimulusEngine: {
        scheduleCheck: vi.fn().mockReturnValue("check-123"),
      },
    };
  }

  beforeEach(() => {
    vi.clearAllMocks();
    mockGetAgentBySession.mockReturnValue("coordinator");
    mockGetProjectContextBySession.mockReturnValue(PROJECT_CONTEXT);
    mockResolveToolProjectContext.mockReturnValue(PROJECT_CONTEXT);
    mockGetProject.mockReturnValue({
      success: true,
      data: { id: "proj-123", name: "adjutant", autoDevelop: true },
    });
    mockEmit.mockClear();
  });

  it("should advance to auto-determined next phase when no targetPhase", async () => {
    const store = createMockStore();
    const deps = createMockDeps();
    const handler = getToolHandler(store, "advance_auto_develop_phase", deps);

    const result = await handler(
      {},
      { sessionId: SESSION_ID },
    );

    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    expect(parsed.success).toBe(true);
    expect(parsed.previousPhase).toBe("analyze");
    expect(parsed.newPhase).toBeDefined();
    expect(parsed.scheduledCheckId).toBe("check-123");

    // Should have updated state
    expect(deps.adjutantState.setMeta).toHaveBeenCalled();
    // Should have scheduled a coordinator wake
    expect(deps.stimulusEngine.scheduleCheck).toHaveBeenCalledWith(
      5_000,
      expect.stringContaining("adjutant"),
    );
    // Should have emitted phase_changed event
    expect(mockEmit).toHaveBeenCalledWith(
      "auto_develop:phase_changed",
      expect.objectContaining({ projectId: "proj-123" }),
    );
  });

  it("should advance to explicit targetPhase when provided", async () => {
    const store = createMockStore();
    const deps = createMockDeps();
    const handler = getToolHandler(store, "advance_auto_develop_phase", deps);

    const result = await handler(
      { targetPhase: "review" },
      { sessionId: SESSION_ID },
    );

    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    expect(parsed.success).toBe(true);
    expect(parsed.previousPhase).toBe("analyze");
    expect(parsed.newPhase).toBe("review");
  });

  it("should reject invalid backward transition", async () => {
    const store = createMockStore();
    const deps = createMockDeps();
    // Current phase is "review"
    deps.adjutantState.getMeta.mockReturnValue("review");
    const handler = getToolHandler(store, "advance_auto_develop_phase", deps);

    const result = await handler(
      { targetPhase: "analyze" },
      { sessionId: SESSION_ID },
    );

    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    expect(parsed.error).toContain("Invalid phase transition");
  });

  it("should allow validate → analyze wrap-around", async () => {
    const store = createMockStore();
    const deps = createMockDeps();
    deps.adjutantState.getMeta.mockReturnValue("validate");
    const handler = getToolHandler(store, "advance_auto_develop_phase", deps);

    const result = await handler(
      { targetPhase: "analyze" },
      { sessionId: SESSION_ID },
    );

    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    expect(parsed.success).toBe(true);
    expect(parsed.newPhase).toBe("analyze");
  });

  it("should error when auto-develop is not enabled", async () => {
    const store = createMockStore();
    const deps = createMockDeps();
    mockGetProject.mockReturnValue({
      success: true,
      data: { id: "proj-123", name: "adjutant", autoDevelop: false },
    });
    const handler = getToolHandler(store, "advance_auto_develop_phase", deps);

    const result = await handler(
      {},
      { sessionId: SESSION_ID },
    );

    const response = result as { content: { type: string; text: string }[] };
    const parsed = JSON.parse(response.content[0].text);
    expect(parsed.error).toContain("not enabled");
  });
});
