/**
 * adj-200 Path B — MCP authoring contract for shareable HTML proposals.
 *
 * Covers:
 *  - adj-200.3.1 (T008): create_proposal / revise_proposal accept optional `html`
 *    (self-contained body, size-capped by Zod) and `public` (auto-publish → public URL).
 *  - adj-200.3.2 (T009): publish_proposal / unpublish_proposal MCP tools.
 *
 * These exercise the registered tool handlers directly, mirroring the harness used by
 * proposal-project-scoping.test.ts (the MCP SDK + mcp-server identity resolution are
 * mocked; the handler is invoked with already-parsed args).
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { z } from "zod";

// Mock logger before imports
vi.mock("../../src/utils/index.js", () => ({
  logInfo: vi.fn(),
  logWarn: vi.fn(),
  logError: vi.fn(),
  logDebug: vi.fn(),
}));

// Mock mcp-server identity/project resolution.
const { mockGetAgentBySession, mockGetProjectContextBySession, mockResolveToolProjectContext } = vi.hoisted(() => ({
  mockGetAgentBySession: vi.fn(),
  mockGetProjectContextBySession: vi.fn(),
  mockResolveToolProjectContext: vi.fn(),
}));

vi.mock("../../src/services/mcp-server.js", () => ({
  getAgentBySession: mockGetAgentBySession,
  getProjectContextBySession: mockGetProjectContextBySession,
  resolveToolProjectContext: mockResolveToolProjectContext,
}));

const { mockGetProject } = vi.hoisted(() => ({ mockGetProject: vi.fn() }));
vi.mock("../../src/services/projects-service.js", () => ({
  getProject: mockGetProject,
}));

// Mock MCP SDK — capture (name, schema, handler) tuples.
const { mockTool, MockMcpServer } = vi.hoisted(() => {
  const mockTool = vi.fn();
  const MockMcpServer = vi.fn().mockImplementation(function () {
    return {
      tool: mockTool,
      connect: vi.fn().mockResolvedValue(undefined),
      close: vi.fn().mockResolvedValue(undefined),
      server: {},
    };
  });
  return { mockTool, MockMcpServer };
});

vi.mock("@modelcontextprotocol/sdk/server/mcp.js", () => ({
  McpServer: MockMcpServer,
}));

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { Proposal, ProposalStore } from "../../src/services/proposal-store.js";
import { registerProposalTools } from "../../src/services/mcp-tools/proposals.js";

// =============================================================================
// Helpers
// =============================================================================

function createMockServer(): McpServer {
  return new MockMcpServer() as unknown as McpServer;
}

const BASE_PROPOSAL: Proposal = {
  id: "test-uuid",
  author: "test-agent",
  title: "Test Proposal",
  description: "A test proposal",
  type: "engineering",
  status: "pending",
  project: "f1e8f895-0000-4000-8000-000000000000",
  createdAt: "2026-06-18T00:00:00Z",
  updatedAt: "2026-06-18T00:00:00Z",
  reviewRound: 0,
  autoGenerated: false,
  isPublic: false,
};

function createMockStore(): ProposalStore {
  return {
    insertProposal: vi.fn().mockImplementation((input: { title: string; description: string; type: string; project: string; author: string }) => ({
      ...BASE_PROPOSAL,
      author: input.author,
      title: input.title,
      description: input.description,
      type: input.type as Proposal["type"],
      project: input.project,
    })),
    getProposal: vi.fn().mockReturnValue({ ...BASE_PROPOSAL }),
    getProposals: vi.fn().mockReturnValue([]),
    updateProposalStatus: vi.fn(),
    insertComment: vi.fn(),
    getComments: vi.fn().mockReturnValue([]),
    reviseProposal: vi.fn().mockImplementation((id: string, input: { title?: string; description?: string; type?: string }) => ({
      ...BASE_PROPOSAL,
      id,
      title: input.title ?? BASE_PROPOSAL.title,
      description: input.description ?? BASE_PROPOSAL.description,
      type: (input.type ?? BASE_PROPOSAL.type) as Proposal["type"],
    })),
    getRevisions: vi.fn().mockReturnValue([]),
    setConfidenceScore: vi.fn(),
    incrementReviewRound: vi.fn(),
    getAutoGeneratedProposals: vi.fn().mockReturnValue([]),
    getProposalsByConfidenceRange: vi.fn().mockReturnValue([]),
    setHtml: vi.fn().mockImplementation((id: string, html: string) => ({ ...BASE_PROPOSAL, id, html })),
    publishProposal: vi.fn().mockImplementation((id: string) => ({
      ...BASE_PROPOSAL,
      id,
      isPublic: true,
      shareToken: "TOKENabc123",
      publishedAt: "2026-06-18T01:00:00Z",
    })),
    unpublishProposal: vi.fn().mockImplementation((id: string) => ({
      ...BASE_PROPOSAL,
      id,
      isPublic: false,
      shareToken: "TOKENabc123",
    })),
    getProposalByToken: vi.fn().mockReturnValue(null),
  };
}

function getToolHandler(store: ProposalStore, toolName: string): (...args: unknown[]) => Promise<unknown> {
  mockTool.mockClear();
  const server = createMockServer();
  registerProposalTools(server, store);
  const call = mockTool.mock.calls.find((c: unknown[]) => c[0] === toolName);
  if (!call) {
    throw new Error(`Tool "${toolName}" not registered. Registered: ${mockTool.mock.calls.map((c: unknown[]) => c[0]).join(", ")}`);
  }
  return call[2] as (...args: unknown[]) => Promise<unknown>;
}

function getToolSchema(store: ProposalStore, toolName: string): z.ZodRawShape {
  mockTool.mockClear();
  const server = createMockServer();
  registerProposalTools(server, store);
  const call = mockTool.mock.calls.find((c: unknown[]) => c[0] === toolName);
  if (!call) throw new Error(`Tool "${toolName}" not registered`);
  return call[1] as z.ZodRawShape;
}

function parseResult(result: unknown): Record<string, unknown> {
  const r = result as { content: { text: string }[] };
  return JSON.parse(r.content[0]!.text) as Record<string, unknown>;
}

const TEST_SESSION_ID = "session-123";
const TEST_PROJECT_CONTEXT = {
  projectId: "f1e8f895-0000-4000-8000-000000000000",
  projectName: "adjutant",
  projectPath: "/path/to/adjutant",
  beadsDir: "/path/to/adjutant/.beads",
};

// =============================================================================
// Tests
// =============================================================================

describe("MCP proposal authoring contract (adj-200 Path B)", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    delete process.env["ADJUTANT_PUBLIC_URL"];
    mockGetProject.mockReturnValue({ success: false, error: { code: "NOT_FOUND", message: "Not found" } });
    mockResolveToolProjectContext.mockImplementation((_explicit: string | undefined, sessionId: string | undefined) => {
      if (sessionId) return mockGetProjectContextBySession(sessionId);
      return undefined;
    });
  });

  // ===========================================================================
  // adj-200.3.1 — create_proposal: html + public
  // ===========================================================================
  describe("create_proposal html + public (adj-200.3.1)", () => {
    it("should persist html via setHtml when html is provided", async () => {
      const store = createMockStore();
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "create_proposal");
      await handler(
        { title: "T", description: "D", type: "engineering", project: "adjutant", html: "<h1>Hi</h1>" },
        { sessionId: TEST_SESSION_ID },
      );

      expect(store.setHtml).toHaveBeenCalledWith("test-uuid", "<h1>Hi</h1>");
    });

    it("should NOT call setHtml when html is omitted", async () => {
      const store = createMockStore();
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "create_proposal");
      await handler(
        { title: "T", description: "D", type: "engineering", project: "adjutant" },
        { sessionId: TEST_SESSION_ID },
      );

      expect(store.setHtml).not.toHaveBeenCalled();
    });

    it("should auto-publish and return a public URL when public is true", async () => {
      const store = createMockStore();
      process.env["ADJUTANT_PUBLIC_URL"] = "https://share.example.com";
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "create_proposal");
      const result = await handler(
        { title: "T", description: "D", type: "engineering", project: "adjutant", html: "<h1>Hi</h1>", public: true },
        { sessionId: TEST_SESSION_ID },
      );

      expect(store.publishProposal).toHaveBeenCalledWith("test-uuid");
      const parsed = parseResult(result);
      expect(parsed["isPublic"]).toBe(true);
      expect(parsed["shareToken"]).toBe("TOKENabc123");
      expect(parsed["publicUrl"]).toBe("https://share.example.com/p/TOKENabc123");
    });

    it("should NOT publish when public is false/omitted", async () => {
      const store = createMockStore();
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "create_proposal");
      const result = await handler(
        { title: "T", description: "D", type: "engineering", project: "adjutant", html: "<h1>Hi</h1>" },
        { sessionId: TEST_SESSION_ID },
      );

      expect(store.publishProposal).not.toHaveBeenCalled();
      const parsed = parseResult(result);
      expect(parsed["publicUrl"]).toBeUndefined();
      expect(parsed["isPublic"]).toBe(false);
    });

    it("should fall back to localhost origin when ADJUTANT_PUBLIC_URL is unset", async () => {
      const store = createMockStore();
      process.env["PORT"] = "4201";
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "create_proposal");
      const result = await handler(
        { title: "T", description: "D", type: "engineering", project: "adjutant", public: true },
        { sessionId: TEST_SESSION_ID },
      );

      const parsed = parseResult(result);
      expect(parsed["publicUrl"]).toBe("http://localhost:4201/p/TOKENabc123");
    });
  });

  // ===========================================================================
  // adj-200.3.1 — create_proposal Zod schema: html size cap
  // ===========================================================================
  describe("create_proposal Zod schema html size cap (adj-200.3.1)", () => {
    it("should reject html that exceeds the size cap", () => {
      const store = createMockStore();
      const schema = z.object(getToolSchema(store, "create_proposal"));
      const oversized = "a".repeat(256 * 1024 + 1);
      const result = schema.safeParse({ title: "T", description: "D", type: "engineering", project: "p", html: oversized });
      expect(result.success).toBe(false);
    });

    it("should accept html within the size cap", () => {
      const store = createMockStore();
      const schema = z.object(getToolSchema(store, "create_proposal"));
      const ok = "<p>" + "a".repeat(1000) + "</p>";
      const result = schema.safeParse({ title: "T", description: "D", type: "engineering", project: "p", html: ok });
      expect(result.success).toBe(true);
    });

    it("should accept omitted html (optional)", () => {
      const store = createMockStore();
      const schema = z.object(getToolSchema(store, "create_proposal"));
      const result = schema.safeParse({ title: "T", description: "D", type: "engineering", project: "p" });
      expect(result.success).toBe(true);
    });
  });

  // ===========================================================================
  // adj-200.3.1 — revise_proposal: html + prior-body snapshot
  // ===========================================================================
  describe("revise_proposal html + snapshot (adj-200.3.1)", () => {
    it("should snapshot the prior body (via reviseProposal) and apply new html via setHtml", async () => {
      const store = createMockStore();
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "revise_proposal");
      const result = await handler(
        { id: "test-uuid", html: "<h2>New body</h2>", changelog: "rewrote body as html" },
        { sessionId: TEST_SESSION_ID },
      );

      // reviseProposal creates the prior-state snapshot (revision row).
      expect(store.reviseProposal).toHaveBeenCalledWith(
        "test-uuid",
        expect.objectContaining({ author: "test-agent", changelog: "rewrote body as html" }),
      );
      // The new html is applied.
      expect(store.setHtml).toHaveBeenCalledWith("test-uuid", "<h2>New body</h2>");
      const parsed = parseResult(result);
      expect(parsed["html"]).toBe("<h2>New body</h2>");
    });

    it("should allow an html-only revision (no title/description/type)", async () => {
      const store = createMockStore();
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "revise_proposal");
      const result = await handler(
        { id: "test-uuid", html: "<p>only html</p>", changelog: "html only" },
        { sessionId: TEST_SESSION_ID },
      );

      const parsed = parseResult(result);
      expect(parsed).not.toHaveProperty("error");
      expect(store.setHtml).toHaveBeenCalled();
    });

    it("should reject when no revisable field (title/description/type/html) is provided", async () => {
      const store = createMockStore();
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "revise_proposal");
      const result = await handler(
        { id: "test-uuid", changelog: "nothing" },
        { sessionId: TEST_SESSION_ID },
      );

      const parsed = parseResult(result);
      expect(parsed).toHaveProperty("error");
      expect(store.reviseProposal).not.toHaveBeenCalled();
      expect(store.setHtml).not.toHaveBeenCalled();
    });

    // adj-ovbhc — silent partial-write hardening. The in-process handler must (a)
    // forward EVERY provided field to the store even alongside a large html, and
    // (b) echo which fields it applied so a field dropped before the handler (the
    // observed client/transport-side truncation on huge multi-field tool calls)
    // is VISIBLE in the result, never silent.
    describe("loud applied-fields echo (adj-ovbhc)", () => {
      it("should forward a large description AND large html together (store is innocent)", async () => {
        const store = createMockStore();
        mockGetAgentBySession.mockReturnValue("test-agent");
        mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

        const bigDescription = "D".repeat(5000);
        const bigHtml = `<h2>Body</h2><p>${"x".repeat(25000)}</p>`;

        const handler = getToolHandler(store, "revise_proposal");
        const result = await handler(
          { id: "test-uuid", description: bigDescription, html: bigHtml, changelog: "big revise" },
          { sessionId: TEST_SESSION_ID },
        );

        // BOTH fields reach their stores — the handler does not drop description.
        expect(store.reviseProposal).toHaveBeenCalledWith(
          "test-uuid",
          expect.objectContaining({ description: bigDescription }),
        );
        expect(store.setHtml).toHaveBeenCalledWith("test-uuid", bigHtml);

        const parsed = parseResult(result);
        expect(parsed).not.toHaveProperty("error");
      });

      it("should echo `applied` listing exactly the content fields that were provided", async () => {
        const store = createMockStore();
        mockGetAgentBySession.mockReturnValue("test-agent");
        mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

        const handler = getToolHandler(store, "revise_proposal");
        const result = await handler(
          { id: "test-uuid", title: "New T", description: "New D", html: "<p>h</p>", changelog: "c" },
          { sessionId: TEST_SESSION_ID },
        );

        const parsed = parseResult(result) as { applied?: Record<string, boolean> };
        expect(parsed.applied).toEqual(
          expect.objectContaining({ title: true, description: true, type: false, html: true }),
        );
      });

      it("should make a DROPPED description visible (applied.description = false) on an html-only call", async () => {
        const store = createMockStore();
        mockGetAgentBySession.mockReturnValue("test-agent");
        mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

        // Mirrors the observed bug: description never arrived; only html present.
        const handler = getToolHandler(store, "revise_proposal");
        const result = await handler(
          { id: "test-uuid", html: "<p>only html</p>", changelog: "html only" },
          { sessionId: TEST_SESSION_ID },
        );

        const parsed = parseResult(result) as { applied?: Record<string, boolean> };
        // The result LOUDLY shows description was not part of this revision.
        expect(parsed.applied?.description).toBe(false);
        expect(parsed.applied?.html).toBe(true);
      });
    });

    it("should auto-publish on revise when public is true and return the public URL", async () => {
      const store = createMockStore();
      process.env["ADJUTANT_PUBLIC_URL"] = "https://share.example.com";
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "revise_proposal");
      const result = await handler(
        { id: "test-uuid", html: "<p>v2</p>", changelog: "publish it", public: true },
        { sessionId: TEST_SESSION_ID },
      );

      expect(store.publishProposal).toHaveBeenCalledWith("test-uuid");
      const parsed = parseResult(result);
      expect(parsed["publicUrl"]).toBe("https://share.example.com/p/TOKENabc123");
    });

    it("should reject html that exceeds the size cap (Zod)", () => {
      const store = createMockStore();
      const schema = z.object(getToolSchema(store, "revise_proposal"));
      const oversized = "a".repeat(256 * 1024 + 1);
      const result = schema.safeParse({ id: "x", html: oversized, changelog: "c" });
      expect(result.success).toBe(false);
    });

    // adj-8efyi — publish-only revise: `public:true` is a valid standalone operation.
    // The tool documents `public` as "publish (or re-publish)", so it must be honored
    // even when no title/description/type/html field is changed.
    it("should publish when only public:true is provided (no content change) and not snapshot a revision", async () => {
      const store = createMockStore();
      process.env["ADJUTANT_PUBLIC_URL"] = "https://share.example.com";
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "revise_proposal");
      const result = await handler(
        { id: "test-uuid", changelog: "just publish", public: true },
        { sessionId: TEST_SESSION_ID },
      );

      const parsed = parseResult(result);
      expect(parsed).not.toHaveProperty("error");
      expect(store.publishProposal).toHaveBeenCalledWith("test-uuid");
      expect(parsed["publicUrl"]).toBe("https://share.example.com/p/TOKENabc123");
      expect(parsed["isPublic"]).toBe(true);
      // A pure publish is not a content revision — no snapshot, no html write.
      expect(store.reviseProposal).not.toHaveBeenCalled();
      expect(store.setHtml).not.toHaveBeenCalled();
    });

    it("should still reject when neither a content field nor public is provided", async () => {
      const store = createMockStore();
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "revise_proposal");
      const result = await handler(
        { id: "test-uuid", changelog: "nothing", public: false },
        { sessionId: TEST_SESSION_ID },
      );

      const parsed = parseResult(result);
      expect(parsed).toHaveProperty("error");
      expect(store.reviseProposal).not.toHaveBeenCalled();
      expect(store.publishProposal).not.toHaveBeenCalled();
    });
  });

  // ===========================================================================
  // adj-200.3.2 — publish_proposal MCP tool
  // ===========================================================================
  describe("publish_proposal (adj-200.3.2)", () => {
    it("should publish, toggle visibility, and return the public URL", async () => {
      const store = createMockStore();
      process.env["ADJUTANT_PUBLIC_URL"] = "https://share.example.com";
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "publish_proposal");
      const result = await handler({ id: "test-uuid" }, { sessionId: TEST_SESSION_ID });

      expect(store.publishProposal).toHaveBeenCalledWith("test-uuid");
      const parsed = parseResult(result);
      expect(parsed).not.toHaveProperty("error");
      expect(parsed["isPublic"]).toBe(true);
      expect(parsed["shareToken"]).toBe("TOKENabc123");
      expect(parsed["publicUrl"]).toBe("https://share.example.com/p/TOKENabc123");
    });

    it("should return a validation error for an unknown id", async () => {
      const store = createMockStore();
      (store.getProposal as ReturnType<typeof vi.fn>).mockReturnValue(null);
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "publish_proposal");
      const result = await handler({ id: "missing" }, { sessionId: TEST_SESSION_ID });

      const parsed = parseResult(result);
      expect(parsed).toHaveProperty("error");
      expect(store.publishProposal).not.toHaveBeenCalled();
    });

    it("should reject when the proposal belongs to a different project", async () => {
      const store = createMockStore();
      (store.getProposal as ReturnType<typeof vi.fn>).mockReturnValue({
        ...BASE_PROPOSAL,
        project: "secret-project",
      });
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "publish_proposal");
      const result = await handler({ id: "test-uuid" }, { sessionId: TEST_SESSION_ID });

      const parsed = parseResult(result);
      expect(parsed).toHaveProperty("error");
      expect((parsed as { error: string }).error).toContain("secret-project");
      expect(store.publishProposal).not.toHaveBeenCalled();
    });

    it("should honor an explicit cross-project projectId override (adj-146)", async () => {
      const OTHER = {
        projectId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
        projectName: "bloomfolio",
        projectPath: "/p/bloom",
        beadsDir: "/p/bloom/.beads",
      };
      const store = createMockStore();
      (store.getProposal as ReturnType<typeof vi.fn>).mockReturnValue({ ...BASE_PROPOSAL, project: OTHER.projectId });
      (store.publishProposal as ReturnType<typeof vi.fn>).mockReturnValue({
        ...BASE_PROPOSAL,
        project: OTHER.projectId,
        isPublic: true,
        shareToken: "TOKENabc123",
      });
      mockGetAgentBySession.mockReturnValue("duke");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);
      mockResolveToolProjectContext.mockImplementation((explicit: string | undefined, sessionId: string | undefined) => {
        if (explicit === OTHER.projectId) return OTHER;
        if (sessionId) return mockGetProjectContextBySession(sessionId);
        return undefined;
      });

      const handler = getToolHandler(store, "publish_proposal");
      const result = await handler({ id: "test-uuid", projectId: OTHER.projectId }, { sessionId: TEST_SESSION_ID });

      const parsed = parseResult(result);
      expect(parsed).not.toHaveProperty("error");
      expect(store.publishProposal).toHaveBeenCalledWith("test-uuid");
    });
  });

  // ===========================================================================
  // adj-200.3.2 — unpublish_proposal MCP tool
  // ===========================================================================
  describe("unpublish_proposal (adj-200.3.2)", () => {
    it("should revoke public access and confirm revocation", async () => {
      const store = createMockStore();
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "unpublish_proposal");
      const result = await handler({ id: "test-uuid" }, { sessionId: TEST_SESSION_ID });

      expect(store.unpublishProposal).toHaveBeenCalledWith("test-uuid");
      const parsed = parseResult(result);
      expect(parsed).not.toHaveProperty("error");
      expect(parsed["isPublic"]).toBe(false);
      expect(parsed["revoked"]).toBe(true);
    });

    it("should return a validation error for an unknown id", async () => {
      const store = createMockStore();
      (store.getProposal as ReturnType<typeof vi.fn>).mockReturnValue(null);
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "unpublish_proposal");
      const result = await handler({ id: "missing" }, { sessionId: TEST_SESSION_ID });

      const parsed = parseResult(result);
      expect(parsed).toHaveProperty("error");
      expect(store.unpublishProposal).not.toHaveBeenCalled();
    });

    it("should reject when the proposal belongs to a different project", async () => {
      const store = createMockStore();
      (store.getProposal as ReturnType<typeof vi.fn>).mockReturnValue({ ...BASE_PROPOSAL, project: "secret-project" });
      mockGetAgentBySession.mockReturnValue("test-agent");
      mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);

      const handler = getToolHandler(store, "unpublish_proposal");
      const result = await handler({ id: "test-uuid" }, { sessionId: TEST_SESSION_ID });

      const parsed = parseResult(result);
      expect(parsed).toHaveProperty("error");
      expect(store.unpublishProposal).not.toHaveBeenCalled();
    });
  });
});
