/**
 * adj-201.3.1 — get_project_style MCP tool.
 *
 * A read-only MCP tool that returns a project's proposal style guide (brand colors)
 * so an authoring agent can honor the project's brand color in proposal HTML.
 *
 * Contract (spec 059 US2):
 *  - Returns `{ brandColorPrimary, brandColorSecondary }` when a guide is set.
 *  - Returns `null` (NOT an error) when no guide is set — an unset guide is valid.
 *  - Resolves the project via the adj-146 `resolveToolProjectContext` pattern
 *    (explicit `projectId` override → session context fallback), enabling cross-project reads.
 *  - A bad/missing project (no resolvable context) returns a structured validation error.
 *
 * Mirrors the harness in mcp-proposals.test.ts — the MCP SDK + mcp-server identity/project
 * resolution are mocked; the registered tool handler is invoked with already-parsed args.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";

// Mock logger before imports
vi.mock("../../src/utils/index.js", () => ({
  logInfo: vi.fn(),
  logWarn: vi.fn(),
  logError: vi.fn(),
  logDebug: vi.fn(),
}));

// Mock mcp-server identity/project resolution.
const { mockGetAgentBySession, mockGetProjectContextBySession, mockResolveToolProjectContext } = vi.hoisted(() => ({
  mockGetAgentBySession: vi.fn(),
  mockGetProjectContextBySession: vi.fn(),
  mockResolveToolProjectContext: vi.fn(),
}));

vi.mock("../../src/services/mcp-server.js", () => ({
  getAgentBySession: mockGetAgentBySession,
  getProjectContextBySession: mockGetProjectContextBySession,
  resolveToolProjectContext: mockResolveToolProjectContext,
}));

const { mockGetProject, mockGetProjectStyleGuide } = vi.hoisted(() => ({
  mockGetProject: vi.fn(),
  mockGetProjectStyleGuide: vi.fn(),
}));
vi.mock("../../src/services/projects-service.js", () => ({
  getProject: mockGetProject,
  getProjectStyleGuide: mockGetProjectStyleGuide,
}));

// Mock MCP SDK — capture (name, schema, handler) tuples.
const { mockTool, MockMcpServer } = vi.hoisted(() => {
  const mockTool = vi.fn();
  const MockMcpServer = vi.fn().mockImplementation(function () {
    return {
      tool: mockTool,
      connect: vi.fn().mockResolvedValue(undefined),
      close: vi.fn().mockResolvedValue(undefined),
      server: {},
    };
  });
  return { mockTool, MockMcpServer };
});

vi.mock("@modelcontextprotocol/sdk/server/mcp.js", () => ({
  McpServer: MockMcpServer,
}));

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { ProposalStore } from "../../src/services/proposal-store.js";
import { registerProposalTools } from "../../src/services/mcp-tools/proposals.js";

// =============================================================================
// Helpers
// =============================================================================

function createMockServer(): McpServer {
  return new MockMcpServer() as unknown as McpServer;
}

/**
 * Minimal store stub — get_project_style does not touch the proposal store, but
 * registerProposalTools requires one to register all tools. Only the methods the
 * registration path references need to exist.
 */
function createMockStore(): ProposalStore {
  return {
    insertProposal: vi.fn(),
    getProposal: vi.fn().mockReturnValue(null),
    getProposals: vi.fn().mockReturnValue([]),
    updateProposalStatus: vi.fn(),
    insertComment: vi.fn(),
    getComments: vi.fn().mockReturnValue([]),
    reviseProposal: vi.fn(),
    getRevisions: vi.fn().mockReturnValue([]),
    setConfidenceScore: vi.fn(),
    incrementReviewRound: vi.fn(),
    getAutoGeneratedProposals: vi.fn().mockReturnValue([]),
    getProposalsByConfidenceRange: vi.fn().mockReturnValue([]),
    setHtml: vi.fn(),
    publishProposal: vi.fn(),
    unpublishProposal: vi.fn(),
    getProposalByToken: vi.fn().mockReturnValue(null),
  } as unknown as ProposalStore;
}

function getToolHandler(store: ProposalStore, toolName: string): (...args: unknown[]) => Promise<unknown> {
  mockTool.mockClear();
  const server = createMockServer();
  registerProposalTools(server, store);
  const call = mockTool.mock.calls.find((c: unknown[]) => c[0] === toolName);
  if (!call) {
    throw new Error(`Tool "${toolName}" not registered. Registered: ${mockTool.mock.calls.map((c: unknown[]) => c[0]).join(", ")}`);
  }
  return call[2] as (...args: unknown[]) => Promise<unknown>;
}

function parseResult(result: unknown): Record<string, unknown> | null {
  const r = result as { content: { text: string }[] };
  return JSON.parse(r.content[0]!.text) as Record<string, unknown> | null;
}

const TEST_SESSION_ID = "session-123";
const TEST_PROJECT_CONTEXT = {
  projectId: "f1e8f895-0000-4000-8000-000000000000",
  projectName: "adjutant",
  projectPath: "/path/to/adjutant",
  beadsDir: "/path/to/adjutant/.beads",
};

// =============================================================================
// Tests
// =============================================================================

describe("get_project_style MCP tool (adj-201.3.1)", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockGetProject.mockReturnValue({ success: false, error: { code: "NOT_FOUND", message: "Not found" } });
    mockResolveToolProjectContext.mockImplementation((_explicit: string | undefined, sessionId: string | undefined) => {
      if (sessionId) return mockGetProjectContextBySession(sessionId);
      return undefined;
    });
  });

  it("should return the style guide when a guide is set for the session project", async () => {
    const store = createMockStore();
    mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);
    mockGetProjectStyleGuide.mockReturnValue({
      success: true,
      data: { brandColorPrimary: "#00ff00", brandColorSecondary: "#0a0a0a" },
    });

    const handler = getToolHandler(store, "get_project_style");
    const result = await handler({}, { sessionId: TEST_SESSION_ID });

    // Reads via the service, scoped to the resolved project UUID.
    expect(mockGetProjectStyleGuide).toHaveBeenCalledWith(TEST_PROJECT_CONTEXT.projectId);
    const parsed = parseResult(result);
    expect(parsed).not.toHaveProperty("error");
    expect(parsed).toEqual({ brandColorPrimary: "#00ff00", brandColorSecondary: "#0a0a0a" });
  });

  it("should return null (NOT an error) when no guide is set", async () => {
    const store = createMockStore();
    mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);
    mockGetProjectStyleGuide.mockReturnValue({
      success: true,
      data: { brandColorPrimary: null, brandColorSecondary: null },
    });

    const handler = getToolHandler(store, "get_project_style");
    const result = await handler({}, { sessionId: TEST_SESSION_ID });

    const parsed = parseResult(result);
    expect(parsed).toBeNull();
  });

  it("should return null when only the secondary is unset but primary is also null (all-or-nothing)", async () => {
    // The guide is all-or-nothing on its required primary, so primary === null ⇒ no guide ⇒ null.
    const store = createMockStore();
    mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);
    mockGetProjectStyleGuide.mockReturnValue({
      success: true,
      data: { brandColorPrimary: null, brandColorSecondary: null },
    });

    const handler = getToolHandler(store, "get_project_style");
    const result = await handler({}, { sessionId: TEST_SESSION_ID });

    expect(parseResult(result)).toBeNull();
  });

  it("should return the guide with a null secondary when only the primary is set", async () => {
    const store = createMockStore();
    mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);
    mockGetProjectStyleGuide.mockReturnValue({
      success: true,
      data: { brandColorPrimary: "#00ff00", brandColorSecondary: null },
    });

    const handler = getToolHandler(store, "get_project_style");
    const result = await handler({}, { sessionId: TEST_SESSION_ID });

    const parsed = parseResult(result);
    expect(parsed).toEqual({ brandColorPrimary: "#00ff00", brandColorSecondary: null });
  });

  it("should honor an explicit cross-project projectId override (adj-146)", async () => {
    const OTHER = {
      projectId: "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",
      projectName: "bloomfolio",
      projectPath: "/p/bloom",
      beadsDir: "/p/bloom/.beads",
    };
    const store = createMockStore();
    mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);
    mockResolveToolProjectContext.mockImplementation((explicit: string | undefined, sessionId: string | undefined) => {
      if (explicit === OTHER.projectId) return OTHER;
      if (sessionId) return mockGetProjectContextBySession(sessionId);
      return undefined;
    });
    mockGetProjectStyleGuide.mockReturnValue({
      success: true,
      data: { brandColorPrimary: "#ff00ff", brandColorSecondary: null },
    });

    const handler = getToolHandler(store, "get_project_style");
    const result = await handler({ projectId: OTHER.projectId }, { sessionId: TEST_SESSION_ID });

    // Reads the OTHER project's guide, not the session project.
    expect(mockGetProjectStyleGuide).toHaveBeenCalledWith(OTHER.projectId);
    const parsed = parseResult(result);
    expect(parsed).toEqual({ brandColorPrimary: "#ff00ff", brandColorSecondary: null });
  });

  it("should return a validation error when no project context can be resolved", async () => {
    const store = createMockStore();
    // No session context and no explicit projectId ⇒ unresolved ⇒ error.
    mockGetProjectContextBySession.mockReturnValue(undefined);

    const handler = getToolHandler(store, "get_project_style");
    const result = await handler({}, { sessionId: TEST_SESSION_ID });

    const parsed = parseResult(result);
    expect(parsed).toHaveProperty("error");
    expect(mockGetProjectStyleGuide).not.toHaveBeenCalled();
  });

  it("should return a validation error when the project is unknown (service NOT_FOUND)", async () => {
    const store = createMockStore();
    mockGetProjectContextBySession.mockReturnValue(TEST_PROJECT_CONTEXT);
    mockGetProjectStyleGuide.mockReturnValue({
      success: false,
      error: { code: "NOT_FOUND", message: "Project 'x' not found" },
    });

    const handler = getToolHandler(store, "get_project_style");
    const result = await handler({}, { sessionId: TEST_SESSION_ID });

    const parsed = parseResult(result);
    expect(parsed).toHaveProperty("error");
  });

  it("should return a validation error when called without an MCP session", async () => {
    const store = createMockStore();

    const handler = getToolHandler(store, "get_project_style");
    const result = await handler({}, {});

    const parsed = parseResult(result);
    expect(parsed).toHaveProperty("error");
    expect(mockGetProjectStyleGuide).not.toHaveBeenCalled();
  });
});
