import { describe, it, expect } from "vitest";

import { composeProposalDocument } from "../../src/services/proposal-html.js";
import type { Proposal } from "../../src/types/proposals.js";

function makeProposal(overrides: Partial<Proposal> = {}): Proposal {
  return {
    id: "p1",
    author: "agent",
    title: "Sample Proposal",
    description: "# Heading\n\nSome **markdown** body text.",
    type: "engineering",
    status: "pending",
    project: "adjutant",
    createdAt: "2026-06-18T00:00:00Z",
    updatedAt: "2026-06-18T00:00:00Z",
    reviewRound: 0,
    autoGenerated: false,
    isPublic: false,
    ...overrides,
  };
}

/** Resource references that would force an external fetch (NOT navigational <a> links). */
function hasExternalResourceRef(html: string): boolean {
  return (
    /<script\b/i.test(html) ||
    /<link\b/i.test(html) ||
    /\bsrc\s*=\s*['"]?(?:https?:)?\/\//i.test(html) ||
    /url\(\s*['"]?(?:https?:)?\/\//i.test(html) ||
    /@import/i.test(html)
  );
}

describe("composeProposalDocument", () => {
  it("should produce a complete self-contained HTML document", () => {
    const out = composeProposalDocument(makeProposal());
    expect(out).toMatch(/^<!DOCTYPE html>/i);
    expect(out).toMatch(/<html[\s>]/i);
    expect(out).toMatch(/<style[\s>]/i); // inlined styles
    expect(out).toMatch(/<\/html>/i);
  });

  it("should render the agent html body when present", () => {
    const out = composeProposalDocument(
      makeProposal({ html: `<section><h2>Design</h2><p>details</p></section>` }),
    );
    expect(out).toContain("<h2>Design</h2>");
    expect(out).toContain("details");
  });

  it("should render the markdown description when html is absent", () => {
    const out = composeProposalDocument(
      makeProposal({ html: undefined, description: "# Big Title\n\nA paragraph." }),
    );
    expect(out).toMatch(/<h1[\s>]/i);
    expect(out).toContain("Big Title");
    expect(out).toContain("A paragraph.");
  });

  it("should fall back to the markdown render when the html sanitizes to empty (never blank)", () => {
    const out = composeProposalDocument(
      makeProposal({ html: `<script>alert(1)</script>`, description: "Recoverable body text." }),
    );
    expect(out).toContain("Recoverable body text.");
    expect(out.toLowerCase()).not.toContain("alert");
    // body region is non-empty
    expect(out.length).toBeGreaterThan(100);
  });

  it("should sanitize the agent html (no script / on* handlers survive)", () => {
    const out = composeProposalDocument(
      makeProposal({ html: `<p onclick="steal()">visible</p><script>alert(1)</script>` }),
    );
    expect(out).toContain("visible");
    expect(out.toLowerCase()).not.toContain("onclick");
    expect(out).not.toMatch(/<script\b/i);
    expect(out.toLowerCase()).not.toContain("alert");
    expect(out).not.toContain("steal");
  });

  it("should be self-contained — no external resource references", () => {
    const out = composeProposalDocument(
      makeProposal({
        html:
          `<img src="https://evil.example.com/x.png">` +
          `<div style="background:url(https://evil.example.com/bg.png)">x</div>` +
          `<p>body</p>`,
      }),
    );
    expect(hasExternalResourceRef(out)).toBe(false);
    expect(out).not.toContain("evil.example.com");
  });

  it("should keep legitimate navigational links (they are not external resources)", () => {
    const out = composeProposalDocument(
      makeProposal({ html: `<p>see <a href="https://example.com">link</a></p>` }),
    );
    expect(out).toContain('href="https://example.com"');
    expect(hasExternalResourceRef(out)).toBe(false);
  });

  it("should escape the proposal title so it cannot inject markup", () => {
    const out = composeProposalDocument(
      makeProposal({ title: `Evil <script>alert(1)</script>` }),
    );
    // No executable script tag — the title is rendered as escaped text only.
    expect(out).not.toMatch(/<script\b/i);
    expect(out).toContain("Evil &lt;script&gt;");
  });

  it("should use a readable document aesthetic, not the Pip-Boy CRT green theme", () => {
    const out = composeProposalDocument(makeProposal());
    expect(out.toLowerCase()).not.toContain("#00ff00"); // pip-boy green
    // system font stack (no external font fetch)
    expect(out).toMatch(/-apple-system|system-ui/i);
  });

  // adj-200.2.4.1 — the document is rendered on surfaces with NO HTTP headers
  // (iOS WKWebView loadHTMLString, web iframe srcdoc), so the strict CSP must travel
  // INSIDE the document as a <meta>, not only as the public route's HTTP header.
  // The CSP value contains single quotes (e.g. 'none'), so capture from the
  // double-quoted content attribute that composeProposalDocument emits.
  const CSP_META_RE =
    /<meta[^>]+http-equiv=["']Content-Security-Policy["'][^>]*content="([^"]+)"[^>]*>/i;

  it("should embed a CSP <meta> in <head> for defense-in-depth on non-HTTP surfaces", () => {
    const out = composeProposalDocument(makeProposal());

    const metaMatch = CSP_META_RE.exec(out);
    expect(metaMatch).not.toBeNull();

    const policy = metaMatch?.[1] ?? "";
    // Deny by default; re-permit only what a self-contained document needs.
    expect(policy).toContain("default-src 'none'");
    expect(policy).toContain("style-src 'unsafe-inline'");
    expect(policy).toContain("img-src data:");

    // The meta must live in <head> (before </head>) to take effect.
    const metaIdx = out.search(/<meta[^>]+Content-Security-Policy/i);
    expect(metaIdx).toBeGreaterThan(-1);
    expect(metaIdx).toBeLessThan(out.indexOf("</head>"));
  });

  it("should not allow script execution under the embedded CSP (no script-src)", () => {
    const out = composeProposalDocument(makeProposal());
    const policy = CSP_META_RE.exec(out)?.[1] ?? "";
    expect(policy.length).toBeGreaterThan(0);
    // No directive re-permits scripts — default-src 'none' with no script-src override.
    expect(policy).not.toMatch(/script-src[^;]*'unsafe-inline'/i);
    expect(policy).not.toMatch(/script-src[^;]*\bhttps?:/i);
  });
});
