import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import type Database from "better-sqlite3";
import type { ProposalStore } from "../../src/services/proposal-store.js";

let testDir: string;
let db: Database.Database;
let store: ProposalStore;

function freshTestDir(): string {
  const dir = join(tmpdir(), `adjutant-proposal-conf-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

async function setupDb(): Promise<Database.Database> {
  const { createDatabase, runMigrations } = await import("../../src/services/database.js");
  const instance = createDatabase(join(testDir, "test.db"));
  runMigrations(instance);
  return instance;
}

function createTestProposal(overrides?: { project?: string; autoGenerated?: boolean }): string {
  const proposal = store.insertProposal({
    author: "test-agent",
    title: "Test proposal",
    description: "Test description",
    type: "engineering",
    project: overrides?.project ?? "adjutant",
  });

  if (overrides?.autoGenerated) {
    db.prepare("UPDATE proposals SET auto_generated = 1 WHERE id = ?").run(proposal.id);
  }

  return proposal.id;
}

describe("ProposalStore Confidence Methods", () => {
  beforeEach(async () => {
    testDir = freshTestDir();
    db = await setupDb();
    const { createProposalStore } = await import("../../src/services/proposal-store.js");
    store = createProposalStore(db);
  });

  afterEach(() => {
    db.close();
    rmSync(testDir, { recursive: true, force: true });
  });

  describe("setConfidenceScore", () => {
    it("should set confidence score and signals on a proposal", () => {
      const id = createTestProposal();
      const signals = { codeQuality: 80, testCoverage: 70, userAlignment: 90 };

      const result = store.setConfidenceScore(id, 80, signals);

      expect(result).not.toBeNull();
      expect(result!.confidenceScore).toBe(80);
      expect(result!.confidenceSignals).toEqual(signals);
    });

    it("should return null for non-existent proposal", () => {
      const result = store.setConfidenceScore("nonexistent-id", 50, { a: 1 });

      expect(result).toBeNull();
    });

    it("should overwrite previous confidence score", () => {
      const id = createTestProposal();

      store.setConfidenceScore(id, 50, { a: 50 });
      const result = store.setConfidenceScore(id, 90, { a: 90, b: 85 });

      expect(result!.confidenceScore).toBe(90);
      expect(result!.confidenceSignals).toEqual({ a: 90, b: 85 });
    });
  });

  describe("incrementReviewRound", () => {
    it("should increment review_round from 0 to 1", () => {
      const id = createTestProposal();

      const result = store.incrementReviewRound(id);

      expect(result).not.toBeNull();
      expect(result!.reviewRound).toBe(1);
    });

    it("should return null for non-existent proposal", () => {
      const result = store.incrementReviewRound("nonexistent-id");

      expect(result).toBeNull();
    });

    it("should increment cumulatively across multiple calls", () => {
      const id = createTestProposal();

      store.incrementReviewRound(id);
      store.incrementReviewRound(id);
      const result = store.incrementReviewRound(id);

      expect(result!.reviewRound).toBe(3);
    });
  });

  describe("getAutoGeneratedProposals", () => {
    it("should return only auto-generated proposals for a project", () => {
      createTestProposal({ autoGenerated: true, project: "myproject" });
      createTestProposal({ autoGenerated: false, project: "myproject" });

      const results = store.getAutoGeneratedProposals("myproject");

      expect(results.length).toBe(1);
      expect(results[0].autoGenerated).toBe(true);
    });

    it("should return empty array when no auto-generated proposals exist", () => {
      createTestProposal({ autoGenerated: false, project: "adjutant" });

      const results = store.getAutoGeneratedProposals("adjutant");

      expect(results).toEqual([]);
    });

    it("should filter by single project identifier", () => {
      createTestProposal({ autoGenerated: true, project: "proj-a" });
      createTestProposal({ autoGenerated: true, project: "proj-b" });
      createTestProposal({ autoGenerated: true, project: "proj-c" });

      const results = store.getAutoGeneratedProposals("proj-a");

      expect(results.length).toBe(1);
      expect(results[0].project).toBe("proj-a");
    });
  });

  describe("getProposalsByConfidenceRange", () => {
    it("should return proposals within the specified confidence range", () => {
      const id1 = createTestProposal({ project: "proj" });
      const id2 = createTestProposal({ project: "proj" });
      const id3 = createTestProposal({ project: "proj" });

      store.setConfidenceScore(id1, 30, { a: 30 });
      store.setConfidenceScore(id2, 60, { a: 60 });
      store.setConfidenceScore(id3, 90, { a: 90 });

      const results = store.getProposalsByConfidenceRange("proj", 50, 100);

      expect(results.length).toBe(2);
      expect(results.map((r) => r.confidenceScore).sort()).toEqual([60, 90]);
    });

    it("should return empty array when no proposals match the range", () => {
      const id = createTestProposal({ project: "proj" });
      store.setConfidenceScore(id, 20, { a: 20 });

      const results = store.getProposalsByConfidenceRange("proj", 50, 100);

      expect(results).toEqual([]);
    });

    it("should exclude proposals without a confidence score (NULL)", () => {
      createTestProposal({ project: "proj" }); // no confidence score set

      const results = store.getProposalsByConfidenceRange("proj", 0, 100);

      expect(results).toEqual([]);
    });

    it("should filter by single project identifier", () => {
      const id1 = createTestProposal({ project: "proj-a" });
      const id2 = createTestProposal({ project: "proj-b" });

      store.setConfidenceScore(id1, 75, { a: 75 });
      store.setConfidenceScore(id2, 85, { a: 85 });

      const results = store.getProposalsByConfidenceRange("proj-a", 70, 90);

      expect(results.length).toBe(1);
      expect(results[0].project).toBe("proj-a");
    });
  });

  describe("rowToProposal mapping for new fields", () => {
    it("should map new confidence fields with defaults for existing proposals", () => {
      const proposal = store.insertProposal({
        author: "test",
        title: "Test",
        description: "Desc",
        type: "product",
        project: "adjutant",
      });

      const fetched = store.getProposal(proposal.id);

      expect(fetched).not.toBeNull();
      expect(fetched!.reviewRound).toBe(0);
      expect(fetched!.autoGenerated).toBe(false);
      expect(fetched!.confidenceScore).toBeUndefined();
      expect(fetched!.confidenceSignals).toBeUndefined();
    });

    it("should handle malformed confidence_signals JSON gracefully", () => {
      const proposal = store.insertProposal({
        author: "test",
        title: "Test",
        description: "Desc",
        type: "product",
        project: "adjutant",
      });

      // Manually corrupt the JSON
      db.prepare("UPDATE proposals SET confidence_signals = 'not-valid-json' WHERE id = ?").run(proposal.id);

      const fetched = store.getProposal(proposal.id);

      expect(fetched).not.toBeNull();
      expect(fetched!.confidenceSignals).toBeUndefined();
    });
  });
});
