/**
 * adj-201.6.1 — Tests for the proposal-page drift-lint.
 *
 * The drift-lint is the SAFETY NET for the AUTHORING-ONLY enforcement model
 * (spec 059 US5): the server never injects project tokens into a published page, so
 * an agent-authored page can silently drift off-brand, lose dark-mode support, or
 * break a11y basics. `lintProposalPage` statically inspects a composed/published
 * proposal HTML document and reports those drifts.
 *
 * Tests are written FIRST (RED) against the not-yet-implemented module. They feed a
 * REAL `composeProposalDocument(...)` output (the compliant baseline) rather than a
 * hand-crafted doc, so the lint is validated against the actual shipped page shape
 * (testing rule: real data shapes, not assumptions).
 */

import { describe, expect, it } from "vitest";

import { composeProposalDocument } from "../../src/services/proposal-html.js";
import { lintProposalPage } from "../../src/services/proposal-style-lint.js";
import type { Proposal } from "../../src/types/proposals.js";

/** Build a Proposal with the given overrides; sensible defaults for the rest. */
function makeProposal(overrides: Partial<Proposal> = {}): Proposal {
  return {
    id: "prop-1",
    author: "agent-x",
    title: "A Friendly Proposal",
    description: "# Heading\n\nSome **markdown** body text for the proposal.",
    type: "engineering",
    status: "pending",
    project: "adjutant",
    createdAt: "2026-06-18T00:00:00.000Z",
    updatedAt: "2026-06-18T00:00:00.000Z",
    reviewRound: 0,
    autoGenerated: false,
    isPublic: false,
    ...overrides,
  };
}

/** A composed page that embeds a known brand accent color in the body html. */
function compliantPageWithAccent(accent: string): string {
  return composeProposalDocument(
    makeProposal({
      html: `<section><h2>Plan</h2><p style="color: ${accent}">On brand text.</p>
        <button style="background:${accent}">Action</button></section>`,
    }),
  );
}

describe("lintProposalPage", () => {
  // ---- (b) dark-mode support ------------------------------------------------

  it("should pass a compliant composeProposalDocument output (dark-mode + landmarks + lang)", () => {
    const html = composeProposalDocument(makeProposal());

    const result = lintProposalPage(html);

    expect(result.ok).toBe(true);
    expect(result.findings.filter((f) => f.severity === "error")).toHaveLength(0);
  });

  it("should flag no-dark-mode when neither prefers-color-scheme nor a theme toggle is present", () => {
    // A minimal page with lang + landmarks but NO dark-mode mechanism at all.
    const html = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
      <style>body{background:#fff;color:#000}</style></head>
      <body><header><h1>Title</h1></header><main><p>Body</p></main></body></html>`;

    const result = lintProposalPage(html);

    const darkFinding = result.findings.find((f) => f.code === "no-dark-mode");
    expect(darkFinding).toBeDefined();
    expect(darkFinding?.severity).toBe("error");
    expect(result.ok).toBe(false);
  });

  it("should NOT flag no-dark-mode when only a prefers-color-scheme media query is present", () => {
    const html = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
      <style>@media (prefers-color-scheme: light){body{background:#fff}}</style></head>
      <body><header><h1>T</h1></header><main><p>B</p></main></body></html>`;

    const result = lintProposalPage(html);

    expect(result.findings.find((f) => f.code === "no-dark-mode")).toBeUndefined();
  });

  // ---- (a) accent-color presence -------------------------------------------

  it("should flag missing-accent-color when the expected brand color is absent", () => {
    const html = composeProposalDocument(makeProposal()); // no accent in body

    const result = lintProposalPage(html, { expectedBrandColor: "#ff6600" });

    const accentFinding = result.findings.find((f) => f.code === "missing-accent-color");
    expect(accentFinding).toBeDefined();
    expect(accentFinding?.severity).toBe("error");
    expect(result.ok).toBe(false);
  });

  it("should NOT flag missing-accent-color when the expected brand color appears in the doc", () => {
    const html = compliantPageWithAccent("#ff6600");

    const result = lintProposalPage(html, { expectedBrandColor: "#ff6600" });

    expect(result.findings.find((f) => f.code === "missing-accent-color")).toBeUndefined();
    expect(result.ok).toBe(true);
  });

  it("should match accent color case-insensitively", () => {
    const html = compliantPageWithAccent("#AABBCC");

    const result = lintProposalPage(html, { expectedBrandColor: "#aabbcc" });

    expect(result.findings.find((f) => f.code === "missing-accent-color")).toBeUndefined();
  });

  it("should normalize #RGB <-> #RRGGBB when matching the accent color", () => {
    // Doc carries the shorthand #f60; expected is the longhand #ff6600.
    const html = compliantPageWithAccent("#f60");

    const result = lintProposalPage(html, { expectedBrandColor: "#ff6600" });

    expect(result.findings.find((f) => f.code === "missing-accent-color")).toBeUndefined();
  });

  it("should SKIP the accent check entirely when no expectedBrandColor is provided", () => {
    const html = composeProposalDocument(makeProposal());

    const result = lintProposalPage(html); // no opts

    expect(result.findings.find((f) => f.code === "missing-accent-color")).toBeUndefined();
  });

  // ---- (c) a11y basics ------------------------------------------------------

  it("should flag missing-lang when the <html> element has no lang attribute", () => {
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
      <style>@media (prefers-color-scheme: light){body{}}</style></head>
      <body><header><h1>T</h1></header><main><p>B</p></main></body></html>`;

    const result = lintProposalPage(html);

    const langFinding = result.findings.find((f) => f.code === "missing-lang");
    expect(langFinding).toBeDefined();
    expect(langFinding?.severity).toBe("error");
    expect(result.ok).toBe(false);
  });

  it("should flag missing-landmark when there is no <main> or <header> semantic landmark", () => {
    const html = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
      <style>@media (prefers-color-scheme: light){body{}}</style></head>
      <body><div><h1>T</h1></div><div><p>B</p></div></body></html>`;

    const result = lintProposalPage(html);

    const landmarkFinding = result.findings.find((f) => f.code === "missing-landmark");
    expect(landmarkFinding).toBeDefined();
    expect(landmarkFinding?.severity).toBe("error");
  });

  it("should flag a static contrast red-flag: same explicit color and background-color", () => {
    // A blatant invisible-text red-flag the lint can detect statically.
    const html = `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
      <style>@media (prefers-color-scheme: light){body{}}
        .x{color:#ffffff;background-color:#ffffff}</style></head>
      <body><header><h1>T</h1></header><main><p class="x">B</p></main></body></html>`;

    const result = lintProposalPage(html);

    const contrastFinding = result.findings.find((f) => f.code === "contrast-red-flag");
    expect(contrastFinding).toBeDefined();
  });

  // ---- edge cases -----------------------------------------------------------

  it("should report multiple findings at once for a doc that fails several checks", () => {
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8">
      <style>body{background:#fff;color:#000}</style></head>
      <body><div><p>No landmarks, no lang, no dark mode</p></div></body></html>`;

    const result = lintProposalPage(html, { expectedBrandColor: "#123456" });

    const codes = result.findings.map((f) => f.code);
    expect(codes).toContain("missing-lang");
    expect(codes).toContain("missing-landmark");
    expect(codes).toContain("no-dark-mode");
    expect(codes).toContain("missing-accent-color");
    expect(result.ok).toBe(false);
  });

  it("should treat an empty string as a non-compliant doc rather than throwing", () => {
    const result = lintProposalPage("");

    expect(result.ok).toBe(false);
    expect(result.findings.length).toBeGreaterThan(0);
  });

  it("should reject an invalid expectedBrandColor with a clear lint error rather than silently passing", () => {
    const html = composeProposalDocument(makeProposal());

    const result = lintProposalPage(html, { expectedBrandColor: "not-a-color" });

    const badColor = result.findings.find((f) => f.code === "invalid-expected-color");
    expect(badColor).toBeDefined();
    expect(badColor?.severity).toBe("error");
  });
});
