/**
 * Tests for adj-141.3: UUID-only enforcement in proposal creation
 * Tests for adj-141.4: Event bus emissions contain UUID-format projectId
 */
import { describe, it, expect, vi, beforeEach } from "vitest";

// Mock logger before imports
vi.mock("../../src/utils/index.js", () => ({
  logInfo: vi.fn(),
  logWarn: vi.fn(),
  logError: vi.fn(),
  logDebug: vi.fn(),
}));

// Mock mcp-server
const { mockGetAgentBySession, mockGetProjectContextBySession, mockResolveToolProjectContext } = vi.hoisted(() => {
  return {
    mockGetAgentBySession: vi.fn(),
    mockGetProjectContextBySession: vi.fn(),
    mockResolveToolProjectContext: vi.fn(),
  };
});

vi.mock("../../src/services/mcp-server.js", () => ({
  getAgentBySession: mockGetAgentBySession,
  getProjectContextBySession: mockGetProjectContextBySession,
  resolveToolProjectContext: mockResolveToolProjectContext,
}));

// Mock event-bus
const { mockEmit } = vi.hoisted(() => {
  return {
    mockEmit: vi.fn(),
  };
});

vi.mock("../../src/services/event-bus.js", () => ({
  getEventBus: () => ({ emit: mockEmit }),
}));

// Mock proposal-store resolveProjectFilter
vi.mock("../../src/services/proposal-store.js", () => ({
  resolveProjectFilter: vi.fn((p: string) => p),
}));

// Mock projects-service
const { mockGetProject, mockEnableAutoDevelop, mockDisableAutoDevelop } = vi.hoisted(() => {
  return {
    mockGetProject: vi.fn(),
    mockEnableAutoDevelop: vi.fn(),
    mockDisableAutoDevelop: vi.fn(),
  };
});

vi.mock("../../src/services/projects-service.js", () => ({
  enableAutoDevelop: mockEnableAutoDevelop,
  disableAutoDevelop: mockDisableAutoDevelop,
  setVisionContext: vi.fn(),
  clearAutoDevelopPause: vi.fn(),
  getProject: mockGetProject,
}));

// Mock MCP SDK
const { mockTool, MockMcpServer } = vi.hoisted(() => {
  const mockTool = vi.fn();
  const MockMcpServer = vi.fn().mockImplementation(function () {
    return {
      tool: mockTool,
      connect: vi.fn().mockResolvedValue(undefined),
      close: vi.fn().mockResolvedValue(undefined),
      server: {},
    };
  });
  return { mockTool, MockMcpServer };
});

vi.mock("@modelcontextprotocol/sdk/server/mcp.js", () => ({
  McpServer: MockMcpServer,
}));

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { ProposalStore } from "../../src/services/proposal-store.js";
import { registerProposalTools } from "../../src/services/mcp-tools/proposals.js";
import { registerAutoDevelopTools } from "../../src/services/mcp-tools/auto-develop.js";

// =============================================================================
// Helpers
// =============================================================================

const VALID_UUID = "a1b2c3d4-e5f6-7890-abcd-ef1234567890";
const VALID_SHORT_ID = "0e578d15";
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const PROJECT_ID_RE = /^[0-9a-f]{8}(-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})?$/i;

function createMockServer(): McpServer {
  return new MockMcpServer() as unknown as McpServer;
}

function createMockStore(overrides?: Partial<ProposalStore>): ProposalStore {
  return {
    insertProposal: vi.fn().mockReturnValue({
      id: "new-proposal-uuid",
      author: "test-agent",
      title: "Test Proposal",
      description: "A test proposal",
      type: "engineering",
      project: VALID_UUID,
      status: "pending",
      createdAt: "2026-03-24T00:00:00Z",
      updatedAt: "2026-03-24T00:00:00Z",
      reviewRound: 0,
      autoGenerated: false,
    }),
    getProposal: vi.fn().mockReturnValue({
      id: "existing-proposal-uuid",
      author: "test-agent",
      title: "Test Proposal",
      description: "A test proposal",
      type: "engineering",
      project: VALID_UUID,
      status: "pending",
      createdAt: "2026-03-24T00:00:00Z",
      updatedAt: "2026-03-24T00:00:00Z",
      reviewRound: 1,
      autoGenerated: true,
    }),
    getProposals: vi.fn().mockReturnValue([]),
    updateProposalStatus: vi.fn(),
    insertComment: vi.fn(),
    getComments: vi.fn(),
    reviseProposal: vi.fn(),
    getRevisions: vi.fn(),
    setConfidenceScore: vi.fn(),
    incrementReviewRound: vi.fn(),
    getAutoGeneratedProposals: vi.fn(),
    getProposalsByConfidenceRange: vi.fn(),
    ...overrides,
  } as unknown as ProposalStore;
}

/**
 * Extract a tool handler registered with server.tool() from proposal tools.
 */
function getProposalToolHandler(
  store: ProposalStore,
  toolName: string,
): (...args: unknown[]) => Promise<unknown> {
  mockTool.mockClear();
  const server = createMockServer();
  registerProposalTools(server, store);

  const call = mockTool.mock.calls.find(
    (c: unknown[]) => c[0] === toolName,
  );
  if (!call) {
    throw new Error(`Tool "${toolName}" not registered`);
  }
  return call[2] as (...args: unknown[]) => Promise<unknown>;
}

/**
 * Extract a tool handler from auto-develop tools.
 */
function getAutoDevelopToolHandler(
  store: ProposalStore,
  toolName: string,
): (...args: unknown[]) => Promise<unknown> {
  mockTool.mockClear();
  const server = createMockServer();
  registerAutoDevelopTools(server, store);

  const call = mockTool.mock.calls.find(
    (c: unknown[]) => c[0] === toolName,
  );
  if (!call) {
    throw new Error(`Tool "${toolName}" not registered`);
  }
  return call[2] as (...args: unknown[]) => Promise<unknown>;
}

// =============================================================================
// adj-141.3: UUID-only in proposal creation
// =============================================================================

describe("create_proposal UUID enforcement (adj-141.3)", () => {
  const SESSION_ID = "session-123";

  beforeEach(() => {
    vi.clearAllMocks();
    mockGetAgentBySession.mockReturnValue("test-agent");
    // resolveToolProjectContext delegates to getProjectContextBySession when no explicit projectId (adj-146)
    mockResolveToolProjectContext.mockImplementation((_explicitProjectId: string | undefined, sessionId: string | undefined) => {
      if (sessionId) return mockGetProjectContextBySession(sessionId);
      return undefined;
    });
  });

  it("should create proposal when projectContext.projectId is a valid UUID", async () => {
    mockGetProjectContextBySession.mockReturnValue({
      projectId: VALID_UUID,
      projectName: "adjutant",
      projectPath: "/code/adjutant",
      beadsDir: "/code/adjutant/.beads",
    });

    const store = createMockStore();
    const handler = getProposalToolHandler(store, "create_proposal");

    const result = await handler(
      { title: "Test", description: "A test", type: "engineering", project: "anything" },
      { sessionId: SESSION_ID },
    ) as { content: { text: string }[] };

    const parsed = JSON.parse(result.content[0].text);
    expect(parsed.error).toBeUndefined();
    expect(parsed.id).toBe("new-proposal-uuid");
    expect(store.insertProposal).toHaveBeenCalledWith(
      expect.objectContaining({ project: VALID_UUID }),
    );
  });

  it("should create proposal when projectContext.projectId is a truncated 8-char hex ID (adj-159)", async () => {
    mockGetProjectContextBySession.mockReturnValue({
      projectId: VALID_SHORT_ID,
      projectName: "adjutant",
      projectPath: "/code/adjutant",
      beadsDir: "/code/adjutant/.beads",
    });

    const store = createMockStore();
    const handler = getProposalToolHandler(store, "create_proposal");

    const result = await handler(
      { title: "Test", description: "A test", type: "engineering", project: "anything" },
      { sessionId: SESSION_ID },
    ) as { content: { text: string }[] };

    const parsed = JSON.parse(result.content[0].text);
    expect(parsed.error).toBeUndefined();
    expect(parsed.id).toBe("new-proposal-uuid");
    expect(store.insertProposal).toHaveBeenCalledWith(
      expect.objectContaining({ project: VALID_SHORT_ID }),
    );
  });

  it("should reject proposal creation when projectContext.projectId is a name string (not UUID)", async () => {
    mockGetProjectContextBySession.mockReturnValue({
      projectId: "adjutant",  // name, not UUID
      projectName: "adjutant",
      projectPath: "/code/adjutant",
      beadsDir: "/code/adjutant/.beads",
    });

    const store = createMockStore();
    const handler = getProposalToolHandler(store, "create_proposal");

    const result = await handler(
      { title: "Test", description: "A test", type: "engineering", project: "adjutant" },
      { sessionId: SESSION_ID },
    ) as { content: { text: string }[] };

    const parsed = JSON.parse(result.content[0].text);
    expect(parsed.error).toContain("Project ID must be a UUID");
    expect(store.insertProposal).not.toHaveBeenCalled();
  });

  it("should ignore client-supplied project and use server-resolved UUID", async () => {
    mockGetProjectContextBySession.mockReturnValue({
      projectId: VALID_UUID,
      projectName: "adjutant",
      projectPath: "/code/adjutant",
      beadsDir: "/code/adjutant/.beads",
    });

    const store = createMockStore();
    const handler = getProposalToolHandler(store, "create_proposal");

    // Client passes a name string — should be ignored in favor of UUID
    await handler(
      { title: "Test", description: "A test", type: "engineering", project: "client-supplied-name" },
      { sessionId: SESSION_ID },
    );

    expect(store.insertProposal).toHaveBeenCalledWith(
      expect.objectContaining({ project: VALID_UUID }),
    );
  });
});

// =============================================================================
// adj-141.4: Event bus emissions use UUID-format projectId
// =============================================================================

describe("event bus emissions use UUID projectId (adj-141.4)", () => {
  const SESSION_ID = "session-456";
  const PROJECT_CONTEXT = {
    projectId: VALID_UUID,
    projectName: "adjutant",
    projectPath: "/code/adjutant",
    beadsDir: "/code/adjutant/.beads",
  };

  beforeEach(() => {
    vi.clearAllMocks();
    mockGetAgentBySession.mockReturnValue("reviewer-agent");
    mockGetProjectContextBySession.mockReturnValue(PROJECT_CONTEXT);
    mockResolveToolProjectContext.mockReturnValue(PROJECT_CONTEXT);
    mockGetProject.mockReturnValue({
      success: true,
      data: { id: VALID_UUID, name: "adjutant", autoDevelop: true },
    });
    mockEnableAutoDevelop.mockReturnValue({ success: true });
    mockDisableAutoDevelop.mockReturnValue({ success: true });
    mockEmit.mockClear();
  });

  it("should emit proposal:scored with UUID projectId (not proposal.project)", async () => {
    const store = createMockStore();
    const handler = getAutoDevelopToolHandler(store, "score_proposal");

    await handler(
      {
        proposalId: "existing-proposal-uuid",
        score: 0.85,
        classification: "accept",
        signals: { feasibility: 0.9, impact: 0.8 },
      },
      { sessionId: SESSION_ID },
    );

    const scoredCall = mockEmit.mock.calls.find(
      (c: unknown[]) => c[0] === "proposal:scored",
    );
    expect(scoredCall).toBeDefined();
    const eventData = scoredCall![1] as { projectId: string };
    expect(eventData.projectId).toBe(VALID_UUID);
    expect(UUID_RE.test(eventData.projectId)).toBe(true);
  });

  it("should emit project:auto_develop_enabled with UUID projectId", async () => {
    const store = createMockStore();
    const handler = getAutoDevelopToolHandler(store, "enable_auto_develop");

    await handler({}, { sessionId: SESSION_ID });

    const enabledCall = mockEmit.mock.calls.find(
      (c: unknown[]) => c[0] === "project:auto_develop_enabled",
    );
    expect(enabledCall).toBeDefined();
    const eventData = enabledCall![1] as { projectId: string };
    expect(eventData.projectId).toBe(VALID_UUID);
    expect(UUID_RE.test(eventData.projectId)).toBe(true);
  });

  it("should emit project:auto_develop_disabled with UUID projectId", async () => {
    const store = createMockStore();
    const handler = getAutoDevelopToolHandler(store, "disable_auto_develop");

    await handler({}, { sessionId: SESSION_ID });

    const disabledCall = mockEmit.mock.calls.find(
      (c: unknown[]) => c[0] === "project:auto_develop_disabled",
    );
    expect(disabledCall).toBeDefined();
    const eventData = disabledCall![1] as { projectId: string };
    expect(eventData.projectId).toBe(VALID_UUID);
    expect(UUID_RE.test(eventData.projectId)).toBe(true);
  });
});
