import { randomUUID } from "node:crypto";
import type Database from "better-sqlite3";
import type {
  Proposal,
  ProposalRow,
  ProposalStatus,
  ProposalType,
  ProposalComment,
  ProposalCommentRow,
  ProposalRevision,
  ProposalRevisionRow,
} from "../types/proposals.js";
import { listProjects } from "./projects-service.js";
import { logInfo, logWarn } from "../utils/index.js";

function rowToProposal(row: ProposalRow): Proposal {
  let confidenceSignals: Record<string, number> | undefined;
  if (row.confidence_signals) {
    try {
      confidenceSignals = JSON.parse(row.confidence_signals) as Record<string, number>;
    } catch {
      confidenceSignals = undefined;
    }
  }

  return {
    id: row.id,
    author: row.author,
    title: row.title,
    description: row.description,
    type: row.type as ProposalType,
    status: row.status as ProposalStatus,
    project: row.project,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    confidenceScore: row.confidence_score ?? undefined,
    reviewRound: row.review_round ?? 0,
    autoGenerated: (row.auto_generated ?? 0) === 1,
    confidenceSignals,
  };
}

function rowToComment(row: ProposalCommentRow): ProposalComment {
  return {
    id: row.id,
    proposalId: row.proposal_id,
    author: row.author,
    body: row.body,
    createdAt: row.created_at,
  };
}

function rowToRevision(row: ProposalRevisionRow): ProposalRevision {
  return {
    id: row.id,
    proposalId: row.proposal_id,
    revisionNumber: row.revision_number,
    author: row.author,
    title: row.title,
    description: row.description,
    type: row.type as ProposalType,
    changelog: row.changelog,
    createdAt: row.created_at,
  };
}

interface InsertCommentInput {
  proposalId: string;
  author: string;
  body: string;
}

interface ReviseProposalInput {
  author: string;
  title?: string | undefined;
  description?: string | undefined;
  type?: ProposalType | undefined;
  changelog: string;
}

interface InsertProposalInput {
  author: string;
  title: string;
  description: string;
  type: ProposalType;
  project: string;
}

interface GetProposalsOptions {
  status?: ProposalStatus | undefined;
  type?: ProposalType | undefined;
  /** Project UUID to filter by. After adj-141.1 migration, all proposals store UUID. */
  project?: string | undefined;
}

export interface ProposalStore {
  insertProposal(input: InsertProposalInput): Proposal;
  getProposal(id: string): Proposal | null;
  getProposals(opts?: GetProposalsOptions): Proposal[];
  updateProposalStatus(id: string, status: ProposalStatus): Proposal | null;
  insertComment(input: InsertCommentInput): ProposalComment;
  getComments(proposalId: string): ProposalComment[];
  reviseProposal(id: string, input: ReviseProposalInput): Proposal | null;
  getRevisions(proposalId: string): ProposalRevision[];
  setConfidenceScore(id: string, score: number, signals: Record<string, number>): Proposal | null;
  incrementReviewRound(id: string): Proposal | null;
  getAutoGeneratedProposals(project: string): Proposal[];
  getProposalsByConfidenceRange(project: string, min: number, max: number): Proposal[];
}

export function createProposalStore(db: Database.Database): ProposalStore {
  const insertStmt = db.prepare(`
    INSERT INTO proposals (id, author, title, description, type, project, status, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?, 'pending', datetime('now'), datetime('now'))
  `);

  const getByIdStmt = db.prepare("SELECT * FROM proposals WHERE id = ?");

  const updateStatusStmt = db.prepare(`
    UPDATE proposals SET status = ?, updated_at = datetime('now') WHERE id = ?
  `);

  // Comment statements
  const insertCommentStmt = db.prepare(`
    INSERT INTO proposal_comments (id, proposal_id, author, body, created_at)
    VALUES (?, ?, ?, ?, datetime('now'))
  `);

  const getCommentByIdStmt = db.prepare("SELECT * FROM proposal_comments WHERE id = ?");

  const getCommentsByProposalStmt = db.prepare(
    "SELECT * FROM proposal_comments WHERE proposal_id = ? ORDER BY created_at ASC, rowid ASC",
  );

  // Revision statements
  const insertRevisionStmt = db.prepare(`
    INSERT INTO proposal_revisions (id, proposal_id, revision_number, author, title, description, type, changelog, created_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))
  `);

  const maxRevisionNumberStmt = db.prepare(
    "SELECT MAX(revision_number) AS max_rev FROM proposal_revisions WHERE proposal_id = ?",
  );

  const getRevisionsByProposalStmt = db.prepare(
    "SELECT * FROM proposal_revisions WHERE proposal_id = ? ORDER BY revision_number ASC",
  );

  const updateProposalContentStmt = db.prepare(`
    UPDATE proposals SET title = ?, description = ?, type = ?, updated_at = datetime('now') WHERE id = ?
  `);

  return {
    insertProposal(input: InsertProposalInput): Proposal {
      const id = randomUUID();
      insertStmt.run(id, input.author, input.title, input.description, input.type, input.project);
      const row = getByIdStmt.get(id) as ProposalRow;
      return rowToProposal(row);
    },

    getProposal(id: string): Proposal | null {
      const row = getByIdStmt.get(id) as ProposalRow | undefined;
      return row !== undefined ? rowToProposal(row) : null;
    },

    getProposals(opts?: GetProposalsOptions): Proposal[] {
      const conditions: string[] = [];
      const params: unknown[] = [];

      if (opts?.status !== undefined) {
        conditions.push("status = ?");
        params.push(opts.status);
      }

      if (opts?.type !== undefined) {
        conditions.push("type = ?");
        params.push(opts.type);
      }

      if (opts?.project !== undefined) {
        // Include proposals with matching project AND unscoped proposals (empty/null project)
        conditions.push("(project = ? OR project IS NULL OR project = '')");
        params.push(opts.project);
      }

      const where = conditions.length > 0 ? `WHERE ${conditions.join(" AND ")}` : "";
      const sql = `SELECT * FROM proposals ${where} ORDER BY created_at DESC, rowid DESC`;
      const rows = db.prepare(sql).all(...params) as ProposalRow[];
      return rows.map(rowToProposal);
    },

    updateProposalStatus(id: string, status: ProposalStatus): Proposal | null {
      const result = updateStatusStmt.run(status, id);
      if (result.changes === 0) return null;
      const row = getByIdStmt.get(id) as ProposalRow;
      return rowToProposal(row);
    },

    insertComment(input: InsertCommentInput): ProposalComment {
      const id = randomUUID();
      insertCommentStmt.run(id, input.proposalId, input.author, input.body);
      const row = getCommentByIdStmt.get(id) as ProposalCommentRow;
      return rowToComment(row);
    },

    getComments(proposalId: string): ProposalComment[] {
      const rows = getCommentsByProposalStmt.all(proposalId) as ProposalCommentRow[];
      return rows.map(rowToComment);
    },

    reviseProposal(id: string, input: ReviseProposalInput): Proposal | null {
      // Read current proposal
      const currentRow = getByIdStmt.get(id) as ProposalRow | undefined;
      if (currentRow === undefined) return null;

      const current = rowToProposal(currentRow);

      // Determine next revision number
      const maxRow = maxRevisionNumberStmt.get(id) as { max_rev: number | null };
      const nextRevNumber = (maxRow.max_rev ?? 0) + 1;

      // Snapshot the current state into revisions
      const revId = randomUUID();
      insertRevisionStmt.run(
        revId,
        id,
        nextRevNumber,
        input.author,
        current.title,
        current.description,
        current.type,
        input.changelog,
      );

      // Update the proposal with new values (only fields provided)
      const newTitle = input.title ?? current.title;
      const newDescription = input.description ?? current.description;
      const newType = input.type ?? current.type;
      updateProposalContentStmt.run(newTitle, newDescription, newType, id);

      // Return the updated proposal
      const updatedRow = getByIdStmt.get(id) as ProposalRow;
      return rowToProposal(updatedRow);
    },

    getRevisions(proposalId: string): ProposalRevision[] {
      const rows = getRevisionsByProposalStmt.all(proposalId) as ProposalRevisionRow[];
      return rows.map(rowToRevision);
    },

    setConfidenceScore(id: string, score: number, signals: Record<string, number>): Proposal | null {
      const row = getByIdStmt.get(id) as ProposalRow | undefined;
      if (!row) return null;

      const signalsJson = JSON.stringify(signals);
      db.prepare(
        "UPDATE proposals SET confidence_score = ?, confidence_signals = ?, updated_at = datetime('now') WHERE id = ?",
      ).run(score, signalsJson, id);

      const updated = getByIdStmt.get(id) as ProposalRow;
      return rowToProposal(updated);
    },

    incrementReviewRound(id: string): Proposal | null {
      const row = getByIdStmt.get(id) as ProposalRow | undefined;
      if (!row) return null;

      db.prepare(
        "UPDATE proposals SET review_round = review_round + 1, updated_at = datetime('now') WHERE id = ?",
      ).run(id);

      const updated = getByIdStmt.get(id) as ProposalRow;
      return rowToProposal(updated);
    },

    getAutoGeneratedProposals(project: string): Proposal[] {
      const sql = "SELECT * FROM proposals WHERE auto_generated = 1 AND project = ? ORDER BY created_at DESC, rowid DESC";
      const rows = db.prepare(sql).all(project) as ProposalRow[];
      return rows.map(rowToProposal);
    },

    getProposalsByConfidenceRange(project: string, min: number, max: number): Proposal[] {
      const sql = "SELECT * FROM proposals WHERE confidence_score >= ? AND confidence_score <= ? AND project = ? ORDER BY confidence_score DESC, created_at DESC";
      const rows = db.prepare(sql).all(min, max, project) as ProposalRow[];
      return rows.map(rowToProposal);
    },
  };
}

/**
 * @deprecated After adj-141.1 migration, all proposals store UUID. Use project UUID directly.
 * Resolve a project filter string (name or UUID) into the project UUID.
 */
export function resolveProjectFilter(project: string | undefined): string | undefined {
  if (!project) return undefined;
  const result = listProjects();
  if (!result.success || !result.data) {
    logWarn("resolveProjectFilter: project lookup failed, using raw value", { project });
    return project;
  }
  const match = result.data.find((p) => p.id === project || p.name === project);
  if (!match) {
    logWarn("resolveProjectFilter: project not found in registry", { project });
    return project;
  }
  return match.id;
}

// UUID v4 pattern: 8-4-4-4-12 hex chars with dashes (36 chars total)
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Check if a string looks like a UUID.
 */
export function isUUID(value: string): boolean {
  return UUID_REGEX.test(value);
}

/**
 * Migrate legacy proposals that have a project name string instead of a UUID.
 *
 * Before adj-090 added server-side project resolution, proposals stored the
 * project name (e.g., "adjutant") instead of the project UUID. This migration
 * finds those proposals and updates them to use the correct UUID.
 *
 * Safe to call multiple times — already-migrated proposals (with UUIDs) are skipped.
 */
export function migrateProposalProjectNames(db: Database.Database): { migrated: number; skipped: number; warnings: string[] } {
  const result = listProjects();
  if (!result.success || !result.data) {
    logWarn("migrateProposalProjectNames: could not list projects, skipping migration");
    return { migrated: 0, skipped: 0, warnings: ["Could not list projects"] };
  }

  const projects = result.data;

  // Build a name-to-UUID lookup map
  const nameToUUID = new Map<string, string>();
  for (const p of projects) {
    nameToUUID.set(p.name, p.id);
  }

  // Find all proposals where project field is not a UUID
  const allProposals = db.prepare("SELECT id, project FROM proposals").all() as { id: string; project: string }[];

  const updateStmt = db.prepare("UPDATE proposals SET project = ? WHERE id = ?");
  let migrated = 0;
  let skipped = 0;
  const warnings: string[] = [];

  const runMigration = db.transaction(() => {
    for (const row of allProposals) {
      if (isUUID(row.project)) {
        skipped++;
        continue;
      }

      // This is a name-based project field — look up the UUID
      const uuid = nameToUUID.get(row.project);
      if (uuid) {
        updateStmt.run(uuid, row.id);
        migrated++;
      } else {
        const msg = `Proposal ${row.id} has unknown project name "${row.project}" — left unchanged`;
        warnings.push(msg);
        logWarn("migrateProposalProjectNames", { proposalId: row.id, project: row.project });
        skipped++;
      }
    }
  });

  runMigration();

  if (migrated > 0) {
    logInfo("migrateProposalProjectNames: migration complete", { migrated, skipped, warnings: warnings.length });
  }

  return { migrated, skipped, warnings };
}
