/**
 * MCP tools for agent proposal operations.
 *
 * Provides create_proposal and list_proposals tools that agents use to
 * generate and review improvement proposals when idle.
 */

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { getAgentBySession, getProjectContextBySession, resolveToolProjectContext } from "../mcp-server.js";
import type { ProposalStore } from "../proposal-store.js";
import { getProject } from "../projects-service.js";
import { logInfo } from "../../utils/index.js";

/**
 * Project ID format regex: accepts both full UUIDs (8-4-4-4-12 hex with dashes)
 * and truncated hex IDs (8 hex chars, as generated by projects-service generateId()).
 * Used to enforce that project identifiers stored in proposals are machine-generated
 * hex strings, never human-readable project names (adj-141.3, adj-159).
 */
const PROJECT_ID_RE = /^[0-9a-f]{8}(-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})?$/i;

/**
 * Maximum size (in characters) of an agent-authored self-contained `html` body (adj-200).
 * 256 KiB. The bound is enforced at the Zod boundary so an oversized document is rejected
 * before it ever reaches the store. Measured in UTF-16 code units (string length) — a close
 * proxy for bytes for the predominantly-ASCII HTML agents produce; the cap is deliberately
 * generous (a self-contained page with inline CSS + inline SVG is comfortably under it).
 */
const MAX_HTML_CHARS = 256 * 1024;

/**
 * Build the public, no-API-key URL for a published proposal: `<origin>/p/<token>`.
 *
 * MCP tool handlers have no incoming HTTP request to derive the host from (unlike the REST
 * publish route, which uses `req`), so the origin is resolved from configuration:
 *   1. `ADJUTANT_PUBLIC_URL` — the canonical externally-reachable origin (e.g. a tunnel URL).
 *   2. Fallback: `http://localhost:<PORT>` (PORT mirrors the server's listen port, default 4201).
 * Any trailing slash on the configured origin is stripped so the result is never `//p/`.
 * Read at call-time (not module load) so deployment/test env changes take effect.
 */
export function buildPublicProposalUrl(token: string): string {
  const port = process.env["PORT"] ?? "4201";
  const origin = (process.env["ADJUTANT_PUBLIC_URL"] ?? `http://localhost:${port}`).replace(/\/+$/, "");
  return `${origin}/p/${token}`;
}

/**
 * Cross-project validation helper. Returns an error response if the proposal
 * belongs to a different project than the caller's resolved project context.
 *
 * Resolution honors an explicit `projectId` override (adj-154/adj-146): when a
 * caller supplies a projectId, access is checked against THAT project, enabling
 * cross-project operations (e.g. Duke reading a bloomfolio proposal from an
 * adjutant-scoped session). When omitted, falls back to the session's project
 * context — identical to the prior behavior, so existing callers are unaffected.
 * Requires project context — callers without it are rejected.
 */
function validateProjectAccess(
  proposal: { project: string },
  extra: { sessionId?: string },
  explicitProjectId?: string,
): { error: string } | null {
  if (!extra.sessionId) {
    return { error: "Unknown session — not connected via MCP" };
  }
  const projectContext = resolveToolProjectContext(explicitProjectId, extra.sessionId);
  if (!projectContext) {
    return { error: "No project context — cannot access proposals across projects" };
  }
  // Allow access to unscoped legacy proposals (empty/null project field)
  if (!proposal.project) {
    return null;
  }
  // Match against both projectId (UUID) and projectName (human-readable).
  // Proposals created before server-side project resolution (adj-088) stored
  // the project name string; newer ones store the UUID. (adj-090)
  if (proposal.project !== projectContext.projectId && proposal.project !== projectContext.projectName) {
    return { error: `Proposal belongs to project ${proposal.project}, but you are scoped to project ${projectContext.projectId}` };
  }
  return null;
}

export function registerProposalTools(server: McpServer, store: ProposalStore): void {
  // ---------------------------------------------------------------------------
  // create_proposal
  // ---------------------------------------------------------------------------
  server.tool(
    "create_proposal",
    {
      title: z.string().describe("Concise proposal title"),
      description: z.string().describe("Deep description of the improvement: what, why, and how"),
      type: z.enum(["product", "engineering"]).describe("Proposal type: 'product' for UX/product improvements, 'engineering' for refactoring/architecture"),
      project: z.string().describe("Project this proposal is for (e.g., 'adjutant')"),
      projectId: z.string().optional().describe("Project UUID for cross-project operations (defaults to session project)"),
      html: z.string().max(MAX_HTML_CHARS, `html must be at most ${MAX_HTML_CHARS} characters (256 KiB)`).optional().describe("Optional self-contained HTML body for the shareable page view. Sanitized server-side. See the authoring contract below."),
      public: z.boolean().optional().describe("When true, immediately publish the proposal and return a no-API-key public URL (publicUrl)."),
    },
    async ({ title, description, type, project: _clientProject, projectId, html, public: makePublic }, extra) => {
      const agentId = extra.sessionId ? getAgentBySession(extra.sessionId) : undefined;
      if (!agentId) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: "Unknown session — not connected via MCP" }) }],
        };
      }

      // Server-side project resolution — ignore client-supplied project
      const projectContext = resolveToolProjectContext(projectId, extra.sessionId);
      if (!projectContext) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: "No project context — cannot create proposal" }) }],
        };
      }

      // Validate that the resolved project ID is a UUID, not a human-readable name (adj-141.3).
      // This is a safety net — projectContext.projectId SHOULD always be a UUID,
      // but we enforce it here to prevent legacy name strings from leaking into storage.
      if (!PROJECT_ID_RE.test(projectContext.projectId)) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({
            error: `Project ID must be a UUID, got: "${projectContext.projectId}"`,
          }) }],
        };
      }

      const proposal = store.insertProposal({
        author: agentId,
        title,
        description,
        type,
        project: projectContext.projectId,
      });

      // Persist the optional self-contained HTML body (adj-200). The store/composition
      // pipeline sanitizes on render; we persist the raw author html here.
      let current = proposal;
      if (html !== undefined) {
        const withHtml = store.setHtml(proposal.id, html);
        if (withHtml) current = withHtml;
      }

      // Optional auto-publish: generate the share token (if absent), flip visibility, and
      // return the public URL so the agent can hand off a working link immediately.
      let publicUrl: string | undefined;
      if (makePublic) {
        const published = store.publishProposal(proposal.id);
        if (published) {
          current = published;
          if (published.shareToken) publicUrl = buildPublicProposalUrl(published.shareToken);
        }
      }

      logInfo("create_proposal", { agentId, proposalId: proposal.id, type, title, html: html !== undefined, public: makePublic === true });

      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify({
            id: current.id,
            title: current.title,
            type: current.type,
            project: current.project,
            status: current.status,
            createdAt: current.createdAt,
            isPublic: current.isPublic,
            ...(current.shareToken ? { shareToken: current.shareToken } : {}),
            ...(publicUrl ? { publicUrl } : {}),
          }),
        }],
      };
    },
  );

  // ---------------------------------------------------------------------------
  // get_proposal
  // ---------------------------------------------------------------------------
  server.tool(
    "get_proposal",
    {
      id: z.string().describe("Proposal UUID to fetch"),
      projectId: z.string().optional().describe("Project UUID for cross-project operations (defaults to session project)"),
    },
    async ({ id, projectId }, extra) => {
      const proposal = store.getProposal(id);
      if (!proposal) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: "Proposal not found" }) }],
        };
      }

      // Cross-project validation (adj-072.5.3) — honors explicit projectId (adj-154)
      const accessError = validateProjectAccess(proposal, extra, projectId);
      if (accessError) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify(accessError) }],
        };
      }

      return {
        content: [{ type: "text" as const, text: JSON.stringify(proposal) }],
      };
    },
  );

  // ---------------------------------------------------------------------------
  // discuss_proposal
  // ---------------------------------------------------------------------------
  server.tool(
    "discuss_proposal",
    {
      id: z.string().describe("Proposal UUID to discuss"),
    },
    async ({ id }, extra) => {
      const proposal = store.getProposal(id);
      if (!proposal) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: "Proposal not found" }) }],
        };
      }

      // Cross-project validation (adj-072.5.4: require project context)
      const accessError = validateProjectAccess(proposal, extra);
      if (accessError) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify(accessError) }],
        };
      }

      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify({
            proposal,
            context: "You are reviewing this proposal with the user. Analyze strengths, weaknesses, feasibility, and suggest improvements. Ask clarifying questions via send_message to 'user'.",
          }),
        }],
      };
    },
  );

  // ---------------------------------------------------------------------------
  // comment_on_proposal
  // ---------------------------------------------------------------------------
  server.tool(
    "comment_on_proposal",
    {
      id: z.string().describe("Proposal UUID to comment on"),
      body: z.string().min(1).describe("Comment text"),
    },
    async ({ id, body }, extra) => {
      const agentId = extra.sessionId ? getAgentBySession(extra.sessionId) : undefined;
      if (!agentId) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: "Unknown session — not connected via MCP" }) }],
        };
      }

      const proposal = store.getProposal(id);
      if (!proposal) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: "Proposal not found" }) }],
        };
      }

      // Cross-project validation (adj-072.5.4: require project context)
      const commentAccessError = validateProjectAccess(proposal, extra);
      if (commentAccessError) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify(commentAccessError) }],
        };
      }

      const comment = store.insertComment({
        proposalId: id,
        author: agentId,
        body,
      });

      logInfo("comment_on_proposal", { agentId, proposalId: id, commentId: comment.id });

      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify(comment),
        }],
      };
    },
  );

  // ---------------------------------------------------------------------------
  // list_proposal_comments
  // ---------------------------------------------------------------------------
  server.tool(
    "list_proposal_comments",
    {
      id: z.string().describe("Proposal UUID to list comments for"),
    },
    async ({ id }, extra) => {
      const proposal = store.getProposal(id);
      if (!proposal) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: "Proposal not found" }) }],
        };
      }

      // Cross-project validation (adj-072.5.3)
      const commentsAccessError = validateProjectAccess(proposal, extra);
      if (commentsAccessError) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify(commentsAccessError) }],
        };
      }

      const comments = store.getComments(id);
      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify({ comments, count: comments.length }),
        }],
      };
    },
  );

  // ---------------------------------------------------------------------------
  // revise_proposal
  // ---------------------------------------------------------------------------
  server.tool(
    "revise_proposal",
    {
      id: z.string().describe("Proposal UUID to revise"),
      title: z.string().min(1).optional().describe("New title (optional — omit to keep current)"),
      description: z.string().min(1).optional().describe("New description (optional — omit to keep current)"),
      type: z.enum(["product", "engineering"]).optional().describe("New type (optional — omit to keep current)"),
      html: z.string().max(MAX_HTML_CHARS, `html must be at most ${MAX_HTML_CHARS} characters (256 KiB)`).optional().describe("Replacement self-contained HTML body for the shareable page view. Sanitized server-side. See the authoring contract below."),
      public: z.boolean().optional().describe("When true, publish (or re-publish) the proposal and return a no-API-key public URL (publicUrl)."),
      changelog: z.string().min(1).describe("Description of what changed and why"),
    },
    async ({ id, title, description, type, html, public: makePublic, changelog }, extra) => {
      const agentId = extra.sessionId ? getAgentBySession(extra.sessionId) : undefined;
      if (!agentId) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: "Unknown session — not connected via MCP" }) }],
        };
      }

      if (title === undefined && description === undefined && type === undefined && html === undefined) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: "At least one of title, description, type, or html must be provided" }) }],
        };
      }

      // Cross-project validation (adj-072.5.4: require project context)
      const proposal = store.getProposal(id);
      if (!proposal) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: "Proposal not found" }) }],
        };
      }
      const reviseAccessError = validateProjectAccess(proposal, extra);
      if (reviseAccessError) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify(reviseAccessError) }],
        };
      }

      // reviseProposal snapshots the prior body (title/description/type) into a revision row
      // BEFORE applying the new values — the same snapshot mechanism every other field uses.
      const revised = store.reviseProposal(id, {
        author: agentId,
        title,
        description,
        type,
        changelog,
      });

      if (!revised) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: "Proposal not found" }) }],
        };
      }

      // Apply the replacement HTML body after the snapshot so the revision captures the
      // prior state (adj-200).
      let current = revised;
      if (html !== undefined) {
        const withHtml = store.setHtml(id, html);
        if (withHtml) current = withHtml;
      }

      // Optional (re-)publish — returns the public URL, reusing the existing token if any.
      let publicUrl: string | undefined;
      if (makePublic) {
        const published = store.publishProposal(id);
        if (published) {
          current = published;
          if (published.shareToken) publicUrl = buildPublicProposalUrl(published.shareToken);
        }
      }

      logInfo("revise_proposal", { agentId, proposalId: id, title: current.title, html: html !== undefined, public: makePublic === true });

      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify(publicUrl ? { ...current, publicUrl } : current),
        }],
      };
    },
  );

  // ---------------------------------------------------------------------------
  // list_revisions
  // ---------------------------------------------------------------------------
  server.tool(
    "list_revisions",
    {
      id: z.string().describe("Proposal UUID to list revisions for"),
    },
    async ({ id }, extra) => {
      const proposal = store.getProposal(id);
      if (!proposal) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify({ error: "Proposal not found" }) }],
        };
      }

      // Cross-project validation (adj-072.5.3)
      const revisionsAccessError = validateProjectAccess(proposal, extra);
      if (revisionsAccessError) {
        return {
          content: [{ type: "text" as const, text: JSON.stringify(revisionsAccessError) }],
        };
      }

      const revisions = store.getRevisions(id);
      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify({ revisions, count: revisions.length }),
        }],
      };
    },
  );

  // ---------------------------------------------------------------------------
  // list_proposals
  // ---------------------------------------------------------------------------
  server.tool(
    "list_proposals",
    {
      status: z.enum(["pending", "accepted", "dismissed", "completed"]).optional().describe("Filter by status"),
      type: z.enum(["product", "engineering"]).optional().describe("Filter by type"),
      project: z.string().optional().describe("Filter by project"),
      projectId: z.string().optional().describe("Project UUID for cross-project operations (defaults to session project)"),
    },
    async ({ status, type, project, projectId }, extra) => {
      // After migration (adj-141.1), all proposals store UUID in the project field.
      // When explicit project is provided, use it directly. When omitted, fall back
      // to session context (UUID).
      let resolvedProject: string | undefined;
      if (projectId !== undefined && projectId !== "") {
        // Priority 1: Explicit projectId param (adj-146)
        resolvedProject = projectId;
      } else if (project !== undefined && project !== "") {
        // Priority 2: Legacy project param — look up UUID if a name was passed
        const projectResult = getProject(project);
        resolvedProject = (projectResult.success && projectResult.data) ? projectResult.data.id : project;
      } else if (project === "") {
        // Empty string is an explicit value — pass through (adj-072.5.5)
        resolvedProject = project;
      } else if (extra.sessionId) {
        const projectContext = getProjectContextBySession(extra.sessionId);
        if (projectContext) {
          resolvedProject = projectContext.projectId;
        }
      }
      const proposals = store.getProposals({ status, type, project: resolvedProject });

      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify({
            proposals: proposals.map((p) => ({
              id: p.id,
              author: p.author,
              title: p.title,
              descriptionPreview: p.description.length > 100
                ? p.description.slice(0, 100) + "…"
                : p.description,
              type: p.type,
              project: p.project,
              status: p.status,
              createdAt: p.createdAt,
            })),
            count: proposals.length,
          }),
        }],
      };
    },
  );
}
