import { describe, it, expect, vi, beforeEach } from "vitest";

import type { AdjutantState } from "../../../../src/services/adjutant/state-store.js";
import type { CommunicationManager } from "../../../../src/services/adjutant/communication.js";
import type { BehaviorEvent } from "../../../../src/services/adjutant/behavior-registry.js";
import type { StimulusEngine } from "../../../../src/services/adjutant/stimulus-engine.js";
import type { ProposalStore } from "../../../../src/services/proposal-store.js";
import type { AutoDevelopStore, AutoDevelopCycle } from "../../../../src/services/auto-develop-store.js";
import type { Proposal } from "../../../../src/types/proposals.js";

// Mock projects-service
const { mockGetAutoDevelopProjects, mockGetProject, mockPauseAutoDevelop, mockClearAutoDevelopPause } = vi.hoisted(() => ({
  mockGetAutoDevelopProjects: vi.fn().mockReturnValue({ success: true, data: [] }),
  mockGetProject: vi.fn().mockReturnValue({ success: false }),
  mockPauseAutoDevelop: vi.fn().mockReturnValue({ success: true }),
  mockClearAutoDevelopPause: vi.fn().mockReturnValue({ success: true }),
}));

vi.mock("../../../../src/services/projects-service.js", () => ({
  getAutoDevelopProjects: mockGetAutoDevelopProjects,
  getProject: mockGetProject,
  pauseAutoDevelop: mockPauseAutoDevelop,
  clearAutoDevelopPause: mockClearAutoDevelopPause,
}));

// Mock event-bus
const { mockEmit } = vi.hoisted(() => ({
  mockEmit: vi.fn(),
}));

vi.mock("../../../../src/services/event-bus.js", () => ({
  getEventBus: () => ({ emit: mockEmit }),
}));

// Mock confidence-engine
vi.mock("../../../../src/services/confidence-engine.js", () => ({
  classifyConfidence: (score: number) => {
    if (score >= 80) return "accept";
    if (score >= 60) return "refine";
    if (score >= 40) return "escalate";
    return "dismiss";
  },
}));

// Mock utils (logError)
vi.mock("../../../../src/utils/index.js", () => ({
  logError: vi.fn(),
  logInfo: vi.fn(),
  logWarn: vi.fn(),
}));

// Mock escalation-builder
vi.mock("../../../../src/services/escalation-builder.js", () => ({
  buildEscalationMessage: (projectName: string, proposals: { id: string }[]) => ({
    title: `Vision Update Needed — Project: ${projectName}`,
    body: `Escalation for ${proposals.length} proposal(s)`,
    proposalIds: proposals.map((p) => p.id),
    projectName,
  }),
}));

import {
  createAutoDevelopLoop,
  phaseKey,
  debounceKey,
  lastIdeationKey,
  buildPhaseReason,
  determineNextPhase,
  shouldSkipIdeation,
  shouldPauseExecution,
  isIdeationOnCooldown,
} from "../../../../src/services/adjutant/behaviors/auto-develop-loop.js";
import { dispatchToBehavior } from "../../../helpers/behavior-dispatch.js";

// ---------------------------------------------------------------------------
// Mock factories
// ---------------------------------------------------------------------------

function createMockStimulusEngine(): StimulusEngine {
  return {
    scheduleCheck: vi.fn().mockReturnValue("check-id-123"),
    cancelCheck: vi.fn(),
    onWake: vi.fn(),
    handleCriticalSignal: vi.fn(),
    registerWatch: vi.fn(),
    cancelWatch: vi.fn(),
    triggerWatch: vi.fn(),
    getPendingSchedule: vi.fn().mockReturnValue({ checks: [], watches: [] }),
    destroy: vi.fn(),
  } as unknown as StimulusEngine;
}

function createMockProposalStore(): ProposalStore {
  return {
    insertProposal: vi.fn(),
    getProposal: vi.fn().mockReturnValue(null),
    getProposals: vi.fn().mockReturnValue([]),
    updateProposalStatus: vi.fn(),
    insertComment: vi.fn(),
    getComments: vi.fn().mockReturnValue([]),
    reviseProposal: vi.fn(),
    getRevisions: vi.fn().mockReturnValue([]),
    setConfidenceScore: vi.fn(),
    incrementReviewRound: vi.fn(),
    getAutoGeneratedProposals: vi.fn().mockReturnValue([]),
    getProposalsByConfidenceRange: vi.fn().mockReturnValue([]),
  } as unknown as ProposalStore;
}

function createMockAutoDevelopStore(): AutoDevelopStore {
  const mockCycle: AutoDevelopCycle = {
    id: "cycle-1",
    projectId: "proj-1",
    phase: "analyze",
    startedAt: new Date().toISOString(),
    completedAt: null,
    proposalsGenerated: 0,
    proposalsAccepted: 0,
    proposalsEscalated: 0,
    proposalsDismissed: 0,
  };
  return {
    startCycle: vi.fn().mockReturnValue(mockCycle),
    updateCycle: vi.fn().mockReturnValue(mockCycle),
    completeCycle: vi.fn().mockReturnValue({ ...mockCycle, completedAt: new Date().toISOString() }),
    getActiveCycle: vi.fn().mockReturnValue(null),
    getCycleHistory: vi.fn().mockReturnValue([]),
  };
}

function createMockState(): AdjutantState {
  return {
    getAgentProfile: vi.fn().mockReturnValue(null),
    upsertAgentProfile: vi.fn(),
    getAllAgentProfiles: vi.fn().mockReturnValue([]),
    incrementAssignmentCount: vi.fn(),
    logDecision: vi.fn(),
    getRecentDecisions: vi.fn().mockReturnValue([]),
    getMeta: vi.fn().mockReturnValue(null),
    setMeta: vi.fn(),
    pruneOldDecisions: vi.fn(),
    logSpawn: vi.fn(),
    getSpawnHistory: vi.fn().mockReturnValue([]),
    getAgentSpawnHistory: vi.fn().mockReturnValue([]),
    markDecommissioned: vi.fn(),
    getLastSpawn: vi.fn().mockReturnValue(null),
    countActiveSpawns: vi.fn().mockReturnValue(0),
    markAllDisconnected: vi.fn().mockReturnValue(0),
    recordOutcome: vi.fn(),
    getRecentDecisionsWithOutcomes: vi.fn().mockReturnValue([]),
    getDecisionsForTarget: vi.fn().mockReturnValue([]),
    isCoordinator: vi.fn().mockReturnValue(false),
    getAgentsByRole: vi.fn().mockReturnValue([]),
  } as unknown as AdjutantState;
}

function createMockComm(): CommunicationManager {
  return {
    queueRoutine: vi.fn(),
    sendImportant: vi.fn().mockResolvedValue(undefined),
    escalate: vi.fn().mockResolvedValue(undefined),
    messageAgent: vi.fn().mockResolvedValue(undefined),
    flushRoutineQueue: vi.fn().mockReturnValue([]),
    getRoutineQueueLength: vi.fn().mockReturnValue(0),
  };
}

const MOCK_PROJECT = {
  id: "proj-1",
  name: "test-project",
  path: "/tmp/test",
  mode: "swarm" as const,
  sessions: [],
  createdAt: new Date().toISOString(),
  active: true,
  autoDevelop: true,
  autoDevelopPausedAt: undefined,
  visionContext: "Build a better world",
};

function makeEvent(name: string, data: unknown = {}): BehaviorEvent {
  return { name: name as BehaviorEvent["name"], data, seq: 1 };
}

function makeProposal(overrides: Partial<Proposal> = {}): Proposal {
  return {
    id: "prop-1",
    author: "agent-1",
    title: "Test Proposal",
    description: "A test proposal",
    type: "engineering",
    status: "pending",
    project: "test-project",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    reviewRound: 0,
    autoGenerated: false,
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("AutoDevelopLoop", () => {
  let stimulusEngine: StimulusEngine;
  let proposalStore: ProposalStore;
  let autoDevelopStore: AutoDevelopStore;
  let state: AdjutantState;
  let comm: CommunicationManager;

  beforeEach(() => {
    vi.clearAllMocks();
    stimulusEngine = createMockStimulusEngine();
    proposalStore = createMockProposalStore();
    autoDevelopStore = createMockAutoDevelopStore();
    state = createMockState();
    comm = createMockComm();

    mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [MOCK_PROJECT] });
    mockGetProject.mockReturnValue({ success: true, data: MOCK_PROJECT });
  });

  // =========================================================================
  // Behavior shape
  // =========================================================================

  describe("behavior shape", () => {
    it("should have correct name, triggers, and schedule", () => {
      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      expect(behavior.name).toBe("auto-develop-loop");
      expect(behavior.triggers).toContain("project:auto_develop_enabled");
      expect(behavior.triggers).toContain("bead:closed");
      expect(behavior.triggers).toContain("proposal:scored");
      expect(behavior.schedule).toBe("*/20 * * * *");
      expect(behavior.excludeRoles).toEqual(["coordinator"]);
    });
  });

  // =========================================================================
  // shouldAct
  // =========================================================================

  describe("shouldAct", () => {
    it("should return true for auto_develop_enabled event", () => {
      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", { projectId: "proj-1" });
      expect(behavior.shouldAct(event, state)).toBe(true);
    });

    it("should return true for cron tick when auto-develop projects exist", () => {
      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("bead:closed", { cronTick: true });
      mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [MOCK_PROJECT] });
      expect(behavior.shouldAct(event, state)).toBe(true);
    });

    it("should return false for cron tick when no auto-develop projects", () => {
      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("bead:closed", { cronTick: true });
      mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [] });
      expect(behavior.shouldAct(event, state)).toBe(false);
    });

    it("should return true for bead:closed event (non-cron)", () => {
      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("bead:closed", { id: "adj-001" });
      expect(behavior.shouldAct(event, state)).toBe(true);
    });

    it("should return true for proposal:scored event", () => {
      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("proposal:scored", { proposalId: "prop-1" });
      expect(behavior.shouldAct(event, state)).toBe(true);
    });
  });

  // =========================================================================
  // act — basic scheduling
  // =========================================================================

  describe("act", () => {
    it("should schedule a check for each auto-develop project", async () => {
      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", { projectId: "proj-1" });

      await dispatchToBehavior(behavior, event, state, comm);

      expect(stimulusEngine.scheduleCheck).toHaveBeenCalledOnce();
      expect(state.setMeta).toHaveBeenCalledWith(
        debounceKey("proj-1"),
        "check-id-123",
      );
      expect(state.logDecision).toHaveBeenCalledWith(
        expect.objectContaining({
          behavior: "auto-develop-loop",
          action: "schedule_analyze",
          target: "proj-1",
        }),
      );
    });

    it("should skip paused projects", async () => {
      const pausedProject = {
        ...MOCK_PROJECT,
        autoDevelopPausedAt: new Date().toISOString(),
      };
      mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [pausedProject] });

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", { projectId: "proj-1" });

      await dispatchToBehavior(behavior, event, state, comm);

      expect(stimulusEngine.scheduleCheck).not.toHaveBeenCalled();
    });

    it("should clear debounce key and proceed even when previous check existed (adj-122.10.1)", async () => {
      // The debounce key is now cleared at the start of act(), so the loop
      // can run multiple iterations without stalling.
      vi.mocked(state.getMeta).mockImplementation((key: string) => {
        if (key === debounceKey("proj-1")) return "existing-check-id";
        return null;
      });

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", { projectId: "proj-1" });

      await dispatchToBehavior(behavior, event, state, comm);

      // Debounce key should have been cleared
      expect(state.setMeta).toHaveBeenCalledWith(debounceKey("proj-1"), "");
      // And a new check should be scheduled
      expect(stimulusEngine.scheduleCheck).toHaveBeenCalledOnce();
    });

    it("should start a new cycle when none is active", async () => {
      vi.mocked(autoDevelopStore.getActiveCycle).mockReturnValue(null);

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", {});

      await dispatchToBehavior(behavior, event, state, comm);

      expect(autoDevelopStore.startCycle).toHaveBeenCalledWith("proj-1", "analyze");
    });

    it("should not start a new cycle when one is already active", async () => {
      const existingCycle: AutoDevelopCycle = {
        id: "cycle-existing",
        projectId: "proj-1",
        phase: "analyze",
        startedAt: new Date().toISOString(),
        completedAt: null,
        proposalsGenerated: 0,
        proposalsAccepted: 0,
        proposalsEscalated: 0,
        proposalsDismissed: 0,
      };
      vi.mocked(autoDevelopStore.getActiveCycle).mockReturnValue(existingCycle);

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", {});

      await dispatchToBehavior(behavior, event, state, comm);

      expect(autoDevelopStore.startCycle).not.toHaveBeenCalled();
    });

    it("should return early when no auto-develop projects exist", async () => {
      mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [] });

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", {});

      await dispatchToBehavior(behavior, event, state, comm);

      expect(stimulusEngine.scheduleCheck).not.toHaveBeenCalled();
    });

    it("should emit phase_changed event", async () => {
      const existingCycle: AutoDevelopCycle = {
        id: "cycle-1",
        projectId: "proj-1",
        phase: "analyze",
        startedAt: new Date().toISOString(),
        completedAt: null,
        proposalsGenerated: 0,
        proposalsAccepted: 0,
        proposalsEscalated: 0,
        proposalsDismissed: 0,
      };
      vi.mocked(autoDevelopStore.getActiveCycle).mockReturnValue(existingCycle);

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", {});

      await dispatchToBehavior(behavior, event, state, comm);

      expect(mockEmit).toHaveBeenCalledWith(
        "auto_develop:phase_changed",
        expect.objectContaining({
          projectId: "proj-1",
          cycleId: "cycle-1",
        }),
      );
    });
  });

  // =========================================================================
  // Phase reason building
  // =========================================================================

  describe("buildPhaseReason", () => {
    it("should build analyze reason with proposal counts", () => {
      vi.mocked(proposalStore.getProposals).mockReturnValue([
        makeProposal({ status: "pending" }),
      ]);

      const reason = buildPhaseReason(
        "proj-1", "test-project", "analyze",
        proposalStore, autoDevelopStore, state,
      );

      expect(reason).toContain("AUTO-DEVELOP ANALYZE");
      expect(reason).toContain("test-project");
      expect(reason).toContain("Pending: 1");
    });

    it("should build ideate reason with existing proposals", () => {
      vi.mocked(proposalStore.getProposals).mockReturnValue([
        makeProposal({ id: "prop-1", title: "Existing Proposal" }),
      ]);

      const reason = buildPhaseReason(
        "proj-1", "test-project", "ideate",
        proposalStore, autoDevelopStore, state,
      );

      expect(reason).toContain("AUTO-DEVELOP IDEATE");
      expect(reason).toContain("Existing Proposal");
    });

    it("should build review reason listing pending proposals", () => {
      vi.mocked(proposalStore.getProposals).mockReturnValue([
        makeProposal({ id: "prop-1", title: "Review Me" }),
      ]);

      const reason = buildPhaseReason(
        "proj-1", "test-project", "review",
        proposalStore, autoDevelopStore, state,
      );

      expect(reason).toContain("AUTO-DEVELOP REVIEW");
      expect(reason).toContain("Review Me");
    });

    it("should build gate reason with scored proposals", () => {
      vi.mocked(proposalStore.getProposalsByConfidenceRange).mockReturnValue([
        makeProposal({ id: "prop-1", confidenceScore: 85 }),
      ]);

      const reason = buildPhaseReason(
        "proj-1", "test-project", "gate",
        proposalStore, autoDevelopStore, state,
      );

      expect(reason).toContain("AUTO-DEVELOP GATE");
      expect(reason).toContain("score=85");
    });

    it("should build plan reason with accepted proposals", () => {
      vi.mocked(proposalStore.getProposals).mockReturnValue([
        makeProposal({ id: "prop-1", title: "Plan This", status: "accepted" }),
      ]);

      const reason = buildPhaseReason(
        "proj-1", "test-project", "plan",
        proposalStore, autoDevelopStore, state,
      );

      expect(reason).toContain("AUTO-DEVELOP PLAN");
      expect(reason).toContain("Plan This");
    });

    it("should build execute reason with spawn count", () => {
      vi.mocked(state.countActiveSpawns).mockReturnValue(3);

      const reason = buildPhaseReason(
        "proj-1", "test-project", "execute",
        proposalStore, autoDevelopStore, state,
      );

      expect(reason).toContain("AUTO-DEVELOP EXECUTE");
      expect(reason).toContain("active agent spawns: 3");
    });

    it("should build validate reason with cycle stats", () => {
      const activeCycle: AutoDevelopCycle = {
        id: "cycle-1",
        projectId: "proj-1",
        phase: "validate",
        startedAt: new Date().toISOString(),
        completedAt: null,
        proposalsGenerated: 5,
        proposalsAccepted: 3,
        proposalsEscalated: 1,
        proposalsDismissed: 1,
      };
      vi.mocked(autoDevelopStore.getActiveCycle).mockReturnValue(activeCycle);

      const reason = buildPhaseReason(
        "proj-1", "test-project", "validate",
        proposalStore, autoDevelopStore, state,
      );

      expect(reason).toContain("AUTO-DEVELOP VALIDATE");
      expect(reason).toContain("Proposals generated: 5");
      expect(reason).toContain("Proposals accepted: 3");
    });

    it("should include vision context when available", () => {
      mockGetProject.mockReturnValue({
        success: true,
        data: { ...MOCK_PROJECT, visionContext: "Build amazing things" },
      });

      const reason = buildPhaseReason(
        "proj-1", "test-project", "analyze",
        proposalStore, autoDevelopStore, state,
      );

      expect(reason).toContain("Build amazing things");
    });
  });

  // =========================================================================
  // determineNextPhase
  // =========================================================================

  describe("determineNextPhase", () => {
    it("should transition analyze -> ideate when no proposals exist", () => {
      vi.mocked(proposalStore.getProposals).mockReturnValue([]);
      const result = determineNextPhase("analyze", "proj-1", "test-project", proposalStore);
      expect(result.nextPhase).toBe("ideate");
    });

    it("should transition analyze -> review when pending proposals exist", () => {
      vi.mocked(proposalStore.getProposals).mockImplementation((opts) => {
        if (opts?.status === "pending") return [makeProposal()];
        return [];
      });
      const result = determineNextPhase("analyze", "proj-1", "test-project", proposalStore);
      expect(result.nextPhase).toBe("review");
    });

    it("should transition analyze -> plan when accepted proposals exist", () => {
      vi.mocked(proposalStore.getProposals).mockImplementation((opts) => {
        if (opts?.status === "accepted") return [makeProposal({ status: "accepted" })];
        return [];
      });
      const result = determineNextPhase("analyze", "proj-1", "test-project", proposalStore);
      expect(result.nextPhase).toBe("plan");
    });

    it("should transition ideate -> review", () => {
      const result = determineNextPhase("ideate", "proj-1", "test-project", proposalStore);
      expect(result.nextPhase).toBe("review");
    });

    it("should transition review -> gate", () => {
      const result = determineNextPhase("review", "proj-1", "test-project", proposalStore);
      expect(result.nextPhase).toBe("gate");
    });

    it("should transition plan -> execute", () => {
      const result = determineNextPhase("plan", "proj-1", "test-project", proposalStore);
      expect(result.nextPhase).toBe("execute");
    });

    it("should transition execute -> validate", () => {
      const result = determineNextPhase("execute", "proj-1", "test-project", proposalStore);
      expect(result.nextPhase).toBe("validate");
    });

    it("should transition validate -> analyze", () => {
      const result = determineNextPhase("validate", "proj-1", "test-project", proposalStore);
      expect(result.nextPhase).toBe("analyze");
    });
  });

  // =========================================================================
  // Gate actions
  // =========================================================================

  describe("gate phase decisions", () => {
    it("should accept proposals with score >= 80", () => {
      vi.mocked(proposalStore.getProposalsByConfidenceRange).mockReturnValue([
        makeProposal({ id: "prop-1", confidenceScore: 85 }),
      ]);
      const result = determineNextPhase("gate", "proj-1", "test-project", proposalStore);
      expect(result.nextPhase).toBe("plan");
      expect(result.gateActions).toHaveLength(1);
      expect(result.gateActions![0]).toEqual(
        expect.objectContaining({ action: "accept", proposalId: "prop-1", score: 85 }),
      );
    });

    it("should refine proposals with score 60-79 when under max rounds", () => {
      vi.mocked(proposalStore.getProposalsByConfidenceRange).mockReturnValue([
        makeProposal({ id: "prop-1", confidenceScore: 70, reviewRound: 1 }),
      ]);
      const result = determineNextPhase("gate", "proj-1", "test-project", proposalStore);
      expect(result.nextPhase).toBe("review");
      expect(result.gateActions).toHaveLength(1);
      expect(result.gateActions![0]).toEqual(
        expect.objectContaining({ action: "refine", proposalId: "prop-1", reviewRound: 2 }),
      );
    });

    it("should escalate proposals with score 60-79 at max review rounds", () => {
      vi.mocked(proposalStore.getProposalsByConfidenceRange).mockReturnValue([
        makeProposal({ id: "prop-1", confidenceScore: 65, reviewRound: 3 }),
      ]);
      const result = determineNextPhase("gate", "proj-1", "test-project", proposalStore);
      expect(result.gateActions).toHaveLength(1);
      expect(result.gateActions![0]).toEqual(
        expect.objectContaining({ action: "escalate", proposalId: "prop-1" }),
      );
    });

    it("should escalate proposals with score 40-59", () => {
      vi.mocked(proposalStore.getProposalsByConfidenceRange).mockReturnValue([
        makeProposal({ id: "prop-1", confidenceScore: 45 }),
      ]);
      const result = determineNextPhase("gate", "proj-1", "test-project", proposalStore);
      expect(result.gateActions).toHaveLength(1);
      expect(result.gateActions![0]).toEqual(
        expect.objectContaining({ action: "escalate", proposalId: "prop-1", score: 45 }),
      );
    });

    it("should dismiss proposals with score < 40", () => {
      vi.mocked(proposalStore.getProposalsByConfidenceRange).mockReturnValue([
        makeProposal({ id: "prop-1", confidenceScore: 25 }),
      ]);
      const result = determineNextPhase("gate", "proj-1", "test-project", proposalStore);
      expect(result.gateActions).toHaveLength(1);
      expect(result.gateActions![0]).toEqual(
        expect.objectContaining({ action: "dismiss", proposalId: "prop-1", score: 25 }),
      );
    });

    it("should escalate via comm.escalate when gate encounters escalation-level proposals", async () => {
      // Set phase to gate
      vi.mocked(state.getMeta).mockImplementation((key: string) => {
        if (key === phaseKey("proj-1")) return "gate";
        return null;
      });

      // Provide a scored proposal in the escalation range
      vi.mocked(proposalStore.getProposalsByConfidenceRange).mockReturnValue([
        makeProposal({ id: "prop-1", confidenceScore: 45, title: "Low Confidence Proposal" }),
      ]);
      vi.mocked(proposalStore.getProposal).mockReturnValue(
        makeProposal({ id: "prop-1", confidenceScore: 45, title: "Low Confidence Proposal" }),
      );

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("proposal:scored", {});

      await dispatchToBehavior(behavior, event, state, comm);

      expect(comm.escalate).toHaveBeenCalledWith(
        expect.stringContaining("Escalation"),
      );
      expect(mockEmit).toHaveBeenCalledWith(
        "auto_develop:escalated",
        expect.objectContaining({ projectId: "proj-1" }),
      );
    });
  });

  // =========================================================================
  // Concurrency controls (Task 5)
  // =========================================================================

  describe("concurrency controls", () => {
    it("should skip ideation when maxProposalsInReview reached", () => {
      // 3 pending proposals = at limit (maxProposalsInReview = 3)
      vi.mocked(proposalStore.getProposals).mockReturnValue([
        makeProposal({ id: "p1" }),
        makeProposal({ id: "p2" }),
        makeProposal({ id: "p3" }),
      ]);

      expect(shouldSkipIdeation("proj-1", "test-project", proposalStore)).toBe(true);
    });

    it("should not skip ideation when under limit", () => {
      vi.mocked(proposalStore.getProposals).mockReturnValue([
        makeProposal({ id: "p1" }),
      ]);

      expect(shouldSkipIdeation("proj-1", "test-project", proposalStore)).toBe(false);
    });

    it("should skip ideation in act() and transition to review", async () => {
      // Set phase to ideate
      vi.mocked(state.getMeta).mockImplementation((key: string) => {
        if (key === phaseKey("proj-1")) return "ideate";
        return null;
      });

      // Mock proposal cap reached
      vi.mocked(proposalStore.getProposals).mockReturnValue([
        makeProposal({ id: "p1" }),
        makeProposal({ id: "p2" }),
        makeProposal({ id: "p3" }),
      ]);

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", {});

      await dispatchToBehavior(behavior, event, state, comm);

      // Should set phase to "review"
      expect(state.setMeta).toHaveBeenCalledWith(phaseKey("proj-1"), "review");
      expect(state.logDecision).toHaveBeenCalledWith(
        expect.objectContaining({
          action: "skip_ideation_proposal_cap",
        }),
      );
      // Should NOT schedule a check (skipped to next iteration)
      expect(stimulusEngine.scheduleCheck).not.toHaveBeenCalled();
    });

    it("should pause execution when agent slots full", () => {
      vi.mocked(state.countActiveSpawns).mockReturnValue(8);
      expect(shouldPauseExecution(state)).toBe(true);
    });

    it("should not pause execution when slots available", () => {
      vi.mocked(state.countActiveSpawns).mockReturnValue(3);
      expect(shouldPauseExecution(state)).toBe(false);
    });

    it("should delay at execute phase with backpressure when agent slots full", async () => {
      // Set phase to execute
      vi.mocked(state.getMeta).mockImplementation((key: string) => {
        if (key === phaseKey("proj-1")) return "execute";
        return null;
      });
      vi.mocked(state.countActiveSpawns).mockReturnValue(8);

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("bead:closed", {});

      await dispatchToBehavior(behavior, event, state, comm);

      // Should schedule with backpressure delay (60 seconds)
      expect(stimulusEngine.scheduleCheck).toHaveBeenCalledWith(
        60_000,
        expect.stringContaining("Waiting for agent slots"),
      );
      expect(state.logDecision).toHaveBeenCalledWith(
        expect.objectContaining({
          action: "backpressure_pause",
        }),
      );
    });

    it("should detect ideation cooldown", () => {
      // Set last ideation time to 5 minutes ago (within 10-minute cooldown)
      const fiveMinAgo = String(Date.now() - 300_000);
      vi.mocked(state.getMeta).mockImplementation((key: string) => {
        if (key === lastIdeationKey("proj-1")) return fiveMinAgo;
        return null;
      });

      expect(isIdeationOnCooldown("proj-1", state)).toBe(true);
    });

    it("should not detect cooldown when enough time has passed", () => {
      // Set last ideation time to 15 minutes ago (past 10-minute cooldown)
      const fifteenMinAgo = String(Date.now() - 900_000);
      vi.mocked(state.getMeta).mockImplementation((key: string) => {
        if (key === lastIdeationKey("proj-1")) return fifteenMinAgo;
        return null;
      });

      expect(isIdeationOnCooldown("proj-1", state)).toBe(false);
    });

    it("should skip ideation in act() when cooldown is active", async () => {
      const recentTime = String(Date.now() - 60_000); // 1 minute ago
      vi.mocked(state.getMeta).mockImplementation((key: string) => {
        if (key === phaseKey("proj-1")) return "ideate";
        if (key === lastIdeationKey("proj-1")) return recentTime;
        return null;
      });

      // Must also have proposals under cap to avoid the cap check triggering first
      vi.mocked(proposalStore.getProposals).mockReturnValue([]);

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", {});

      await dispatchToBehavior(behavior, event, state, comm);

      expect(state.logDecision).toHaveBeenCalledWith(
        expect.objectContaining({
          action: "skip_ideation_cooldown",
        }),
      );
      expect(stimulusEngine.scheduleCheck).not.toHaveBeenCalled();
    });
  });

  // =========================================================================
  // Validate phase — cycle completion
  // =========================================================================

  describe("validate phase", () => {
    it("should complete the cycle when in validate phase", async () => {
      const existingCycle: AutoDevelopCycle = {
        id: "cycle-1",
        projectId: "proj-1",
        phase: "validate",
        startedAt: new Date().toISOString(),
        completedAt: null,
        proposalsGenerated: 2,
        proposalsAccepted: 1,
        proposalsEscalated: 0,
        proposalsDismissed: 1,
      };
      vi.mocked(autoDevelopStore.getActiveCycle).mockReturnValue(existingCycle);

      vi.mocked(state.getMeta).mockImplementation((key: string) => {
        if (key === phaseKey("proj-1")) return "validate";
        return null;
      });

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("bead:closed", {});

      await dispatchToBehavior(behavior, event, state, comm);

      expect(autoDevelopStore.completeCycle).toHaveBeenCalledWith("cycle-1");
    });
  });

  // =========================================================================
  // Metadata key helpers
  // =========================================================================

  describe("key helpers", () => {
    it("should generate correct phase key", () => {
      expect(phaseKey("proj-1")).toBe("auto_develop_phase_proj-1");
    });

    it("should generate correct debounce key", () => {
      expect(debounceKey("proj-1")).toBe("auto_develop_debounce_proj-1");
    });

    it("should generate correct last ideation key", () => {
      expect(lastIdeationKey("proj-1")).toBe("auto_develop_last_ideation_proj-1");
    });
  });

  // =========================================================================
  // Regression tests for adj-122.10.x bug fixes
  // =========================================================================

  describe("regression: adj-122.10.1 — debounce key stall", () => {
    it("should run multiple iterations without stalling on debounce", async () => {
      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", { projectId: "proj-1" });

      // First run
      await dispatchToBehavior(behavior, event, state, comm);
      expect(stimulusEngine.scheduleCheck).toHaveBeenCalledOnce();

      vi.clearAllMocks();
      mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [MOCK_PROJECT] });
      mockGetProject.mockReturnValue({ success: true, data: MOCK_PROJECT });

      // Simulate that debounce key is still set from first run
      vi.mocked(state.getMeta).mockImplementation((key: string) => {
        if (key === debounceKey("proj-1")) return "old-check-id";
        return null;
      });

      // Second run — should NOT stall
      await dispatchToBehavior(behavior, event, state, comm);
      expect(stimulusEngine.scheduleCheck).toHaveBeenCalledOnce();
      // Debounce key should be cleared then re-set
      expect(state.setMeta).toHaveBeenCalledWith(debounceKey("proj-1"), "");
    });
  });

  describe("regression: adj-122.10.2 — phase_changed event values", () => {
    it("should emit different previousPhase and newPhase in phase_changed event", async () => {
      // Start in analyze phase
      vi.mocked(state.getMeta).mockImplementation((key: string) => {
        if (key === phaseKey("proj-1")) return "analyze";
        return null;
      });

      // No proposals -> next phase should be "ideate"
      vi.mocked(proposalStore.getProposals).mockReturnValue([]);

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", {});

      await dispatchToBehavior(behavior, event, state, comm);

      // Verify the phase_changed event has different previous and new phases
      expect(mockEmit).toHaveBeenCalledWith(
        "auto_develop:phase_changed",
        expect.objectContaining({
          projectId: "proj-1",
          previousPhase: "analyze",
          newPhase: "ideate",
        }),
      );

      // Phase key should be advanced to the next phase
      expect(state.setMeta).toHaveBeenCalledWith(phaseKey("proj-1"), "ideate");
    });
  });

  describe("regression: adj-122.10.3 — gate escalation pauses auto-develop", () => {
    it("should call pauseAutoDevelop when gate encounters escalation-level proposals", async () => {
      vi.mocked(state.getMeta).mockImplementation((key: string) => {
        if (key === phaseKey("proj-1")) return "gate";
        return null;
      });

      vi.mocked(proposalStore.getProposalsByConfidenceRange).mockReturnValue([
        makeProposal({ id: "prop-1", confidenceScore: 45, title: "Low Confidence" }),
      ]);
      vi.mocked(proposalStore.getProposal).mockReturnValue(
        makeProposal({ id: "prop-1", confidenceScore: 45, title: "Low Confidence" }),
      );

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("proposal:scored", {});

      await dispatchToBehavior(behavior, event, state, comm);

      expect(mockPauseAutoDevelop).toHaveBeenCalledWith("proj-1");
    });
  });

  describe("regression: adj-122.10.5 — maxEpicsInExecution enforcement", () => {
    it("should pause execute phase when epic cap is reached", async () => {
      vi.mocked(state.getMeta).mockImplementation((key: string) => {
        if (key === phaseKey("proj-1")) return "execute";
        return null;
      });

      // Mock 2 accepted proposals (at maxEpicsInExecution limit)
      vi.mocked(proposalStore.getProposals).mockReturnValue([
        makeProposal({ id: "p1", status: "accepted" }),
        makeProposal({ id: "p2", status: "accepted" }),
      ]);

      // Agent slots are available (not backpressure)
      vi.mocked(state.countActiveSpawns).mockReturnValue(2);

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("bead:closed", {});

      await dispatchToBehavior(behavior, event, state, comm);

      expect(state.logDecision).toHaveBeenCalledWith(
        expect.objectContaining({
          action: "epic_cap_pause",
          target: "proj-1",
        }),
      );
    });
  });

  describe("regression: adj-122.10.5 — escalation timeout auto-resume", () => {
    it("should auto-resume projects paused longer than escalationTimeoutMs", async () => {
      const longAgo = new Date(Date.now() - 86_400_001).toISOString(); // Just past 24h
      const pausedProject = {
        ...MOCK_PROJECT,
        autoDevelopPausedAt: longAgo,
      };
      mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [pausedProject] });

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", {});

      await dispatchToBehavior(behavior, event, state, comm);

      expect(mockClearAutoDevelopPause).toHaveBeenCalledWith("proj-1");
      expect(state.setMeta).toHaveBeenCalledWith(phaseKey("proj-1"), "analyze");
      expect(state.logDecision).toHaveBeenCalledWith(
        expect.objectContaining({
          action: "escalation_timeout_resume",
        }),
      );
      // Should proceed to schedule a check (not skip)
      expect(stimulusEngine.scheduleCheck).toHaveBeenCalled();
    });
  });

  describe("regression: adj-122.10.8 — per-project error isolation", () => {
    it("should continue processing other projects when one throws", async () => {
      const project2 = { ...MOCK_PROJECT, id: "proj-2", name: "test-project-2" };
      mockGetAutoDevelopProjects.mockReturnValue({ success: true, data: [MOCK_PROJECT, project2] });

      // Make the first project throw by having getActiveCycle throw
      let callCount = 0;
      vi.mocked(autoDevelopStore.getActiveCycle).mockImplementation((projectId) => {
        callCount++;
        if (projectId === "proj-1") throw new Error("Simulated failure");
        return null;
      });

      const behavior = createAutoDevelopLoop(stimulusEngine, proposalStore, autoDevelopStore);
      const event = makeEvent("project:auto_develop_enabled", {});

      // Should not throw despite proj-1 erroring
      await dispatchToBehavior(behavior, event, state, comm);

      // proj-2 should still have been scheduled
      expect(stimulusEngine.scheduleCheck).toHaveBeenCalledOnce();
      // getActiveCycle should have been called for both projects
      expect(callCount).toBe(2);
    });
  });
});
