import Foundation

/// Type classification for proposals.
public enum ProposalType: String, Codable, CaseIterable, Sendable {
    case product
    case engineering
}

/// Status lifecycle for proposals.
public enum ProposalStatus: String, Codable, CaseIterable, Sendable {
    case pending
    case accepted
    case dismissed
    case completed
}

/// A proposal submitted by an agent for review.
public struct Proposal: Codable, Identifiable, Equatable, Sendable {
    /// Unique identifier (UUID)
    public let id: String
    /// Agent who authored the proposal
    public let author: String
    /// Proposal title
    public let title: String
    /// Detailed description of the proposal
    public let description: String
    /// Classification: product or engineering
    public let type: ProposalType
    /// Current status in the review lifecycle
    public let status: ProposalStatus
    /// ISO 8601 creation timestamp
    public let createdAt: String
    /// ISO 8601 last-update timestamp
    public let updatedAt: String
    /// Composite confidence score (0-100), set after review
    public let confidenceScore: Int?
    /// Number of review rounds completed
    public let reviewRound: Int?
    /// Whether this proposal was auto-generated by the system
    public let autoGenerated: Bool?
    /// Per-dimension confidence signal scores
    public let confidenceSignals: [String: Double]?

    // MARK: - Sharing (adj-200, Path A contract)

    /// Self-contained, sanitized HTML body for the shareable page (nil when the
    /// proposal predates HTML authoring or was never given an html body).
    public let html: String?
    /// Whether the proposal is currently published to its public `/p/:token` page.
    /// Decode-safe optional — absent on legacy payloads; treat nil as not-published.
    public let isPublic: Bool?
    /// Stable share token. Retained across unpublish so a re-publish revives the same
    /// link (Path A contract). nil until the proposal has been published at least once.
    public let shareToken: String?
    /// ISO 8601 timestamp of first publish (nil if never published).
    public let publishedAt: String?

    public init(
        id: String,
        author: String,
        title: String,
        description: String,
        type: ProposalType,
        status: ProposalStatus,
        createdAt: String,
        updatedAt: String,
        confidenceScore: Int? = nil,
        reviewRound: Int? = nil,
        autoGenerated: Bool? = nil,
        confidenceSignals: [String: Double]? = nil,
        html: String? = nil,
        isPublic: Bool? = nil,
        shareToken: String? = nil,
        publishedAt: String? = nil
    ) {
        self.id = id
        self.author = author
        self.title = title
        self.description = description
        self.type = type
        self.status = status
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.confidenceScore = confidenceScore
        self.reviewRound = reviewRound
        self.autoGenerated = autoGenerated
        self.confidenceSignals = confidenceSignals
        self.html = html
        self.isPublic = isPublic
        self.shareToken = shareToken
        self.publishedAt = publishedAt
    }

    /// Convenience: true only when the proposal is currently published.
    /// Normalizes the decode-safe optional `isPublic` (nil → false).
    public var isPublished: Bool { isPublic ?? false }

    /// Classification based on confidence thresholds (matches backend confidence-engine)
    public var classification: String? {
        guard let score = confidenceScore else { return nil }
        if score >= 80 { return "ACCEPT" }
        if score >= 60 { return "REFINE" }
        if score >= 40 { return "ESCALATE" }
        return "DISMISS"
    }

    // Shared date formatters (avoid per-call allocation — adj-6yp4.1)
    private static let isoFormatterFractional: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return f
    }()
    private static let isoFormatterBasic = ISO8601DateFormatter()
    private static let relativeDateFormatter: RelativeDateTimeFormatter = {
        let f = RelativeDateTimeFormatter()
        f.unitsStyle = .abbreviated
        return f
    }()

    /// Parse the createdAt timestamp into a Date
    public var createdDate: Date? {
        Self.isoFormatterFractional.date(from: createdAt)
            ?? Self.isoFormatterBasic.date(from: createdAt)
    }

    /// Display-friendly relative date string
    public var relativeDate: String {
        guard let date = createdDate else { return createdAt }
        return Self.relativeDateFormatter.localizedString(for: date, relativeTo: Date())
    }
}

/// A comment on a proposal.
public struct ProposalComment: Codable, Identifiable, Equatable, Sendable {
    /// Unique identifier (UUID)
    public let id: String
    /// The proposal this comment belongs to
    public let proposalId: String
    /// Author of the comment
    public let author: String
    /// Comment body text
    public let body: String
    /// ISO 8601 creation timestamp
    public let createdAt: String

    public init(
        id: String,
        proposalId: String,
        author: String,
        body: String,
        createdAt: String
    ) {
        self.id = id
        self.proposalId = proposalId
        self.author = author
        self.body = body
        self.createdAt = createdAt
    }

    // Shared date formatters (avoid per-call allocation — adj-6yp4.1)
    private static let isoFormatterFractional: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return f
    }()
    private static let isoFormatterBasic = ISO8601DateFormatter()
    private static let relativeDateFormatter: RelativeDateTimeFormatter = {
        let f = RelativeDateTimeFormatter()
        f.unitsStyle = .abbreviated
        return f
    }()

    /// Parse the createdAt timestamp into a Date
    public var createdDate: Date? {
        Self.isoFormatterFractional.date(from: createdAt)
            ?? Self.isoFormatterBasic.date(from: createdAt)
    }

    /// Display-friendly relative date string
    public var relativeDate: String {
        guard let date = createdDate else { return createdAt }
        return Self.relativeDateFormatter.localizedString(for: date, relativeTo: Date())
    }
}

/// A revision snapshot of a proposal.
public struct ProposalRevision: Codable, Identifiable, Equatable, Sendable {
    /// Unique identifier (UUID)
    public let id: String
    /// The proposal this revision belongs to
    public let proposalId: String
    /// Sequential revision number (1, 2, 3, ...)
    public let revisionNumber: Int
    /// Author who created the revision
    public let author: String
    /// Proposal title at time of revision
    public let title: String
    /// Proposal description at time of revision
    public let description: String
    /// Proposal type at time of revision
    public let type: String
    /// Changelog describing what changed
    public let changelog: String
    /// ISO 8601 creation timestamp
    public let createdAt: String

    public init(
        id: String,
        proposalId: String,
        revisionNumber: Int,
        author: String,
        title: String,
        description: String,
        type: String,
        changelog: String,
        createdAt: String
    ) {
        self.id = id
        self.proposalId = proposalId
        self.revisionNumber = revisionNumber
        self.author = author
        self.title = title
        self.description = description
        self.type = type
        self.changelog = changelog
        self.createdAt = createdAt
    }

    // Shared date formatters (avoid per-call allocation — adj-6yp4.1)
    private static let isoFormatterFractional: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return f
    }()
    private static let isoFormatterBasic = ISO8601DateFormatter()
    private static let relativeDateFormatter: RelativeDateTimeFormatter = {
        let f = RelativeDateTimeFormatter()
        f.unitsStyle = .abbreviated
        return f
    }()

    /// Parse the createdAt timestamp into a Date
    public var createdDate: Date? {
        Self.isoFormatterFractional.date(from: createdAt)
            ?? Self.isoFormatterBasic.date(from: createdAt)
    }

    /// Display-friendly relative date string
    public var relativeDate: String {
        guard let date = createdDate else { return createdAt }
        return Self.relativeDateFormatter.localizedString(for: date, relativeTo: Date())
    }
}

/// Request body for posting a comment on a proposal.
public struct CreateProposalCommentRequest: Encodable, Sendable {
    /// Author of the comment
    public let author: String
    /// Comment body text
    public let body: String

    public init(author: String, body: String) {
        self.author = author
        self.body = body
    }
}

// MARK: - Sharing responses (adj-200, Path A contract)

/// Decoded `data` envelope for `POST /api/proposals/:id/publish` → `{ proposal, publicUrl }`.
struct PublishProposalResponse: Decodable {
    let proposal: Proposal
    let publicUrl: String
}

/// Decoded `data` envelope for `POST /api/proposals/:id/unpublish` → `{ proposal }`.
struct UnpublishProposalResponse: Decodable {
    let proposal: Proposal
}

/// Public result of publishing a proposal: the updated proposal plus its public URL.
public struct PublishProposalResult: Equatable, Sendable {
    /// The updated proposal (now `isPublic == true`).
    public let proposal: Proposal
    /// The full, no-API-key public URL (`<origin>/p/<shareToken>`).
    public let publicUrl: String

    public init(proposal: Proposal, publicUrl: String) {
        self.proposal = proposal
        self.publicUrl = publicUrl
    }
}

/// Request body for updating a proposal's status.
public struct UpdateProposalStatusRequest: Encodable, Sendable {
    /// The new status to set
    public let status: ProposalStatus

    public init(status: ProposalStatus) {
        self.status = status
    }
}
